### ISSUE TITLE
[2.X] Self-signed certificates no longer supported

### ISSUE THREAD

**Issue by bppdddqqqq** [OnionBrowser/iOS-OnionBrowser#111]
1.X used to not exert this behaviour because it allowed us to grant an exception via a prompt that appears before visiting the site
2.X denies access to the site and doesn’t offer any option to skip

**Comment by tladesignz** [comment]
Here is the code from 1.X which ignored TLS errors with whitelisted domains:

https://github.com/OnionBrowser/OnionBrowser/blob/6ec0fdfcb5f44573a5f2a91b1850cea5e02ffbf2/OnionBrowser/OnionBrowser/WebViewController.m#L718

https://github.com/OnionBrowser/OnionBrowser/blob/6ec0fdfcb5f44573a5f2a91b1850cea5e02ffbf2/OnionBrowser/ConnectionKit/CKHTTPConnection.m#L167

It seems rather dangerous, as it seems, we can't just ignore the self-signed-ness of a page's certificate, but will be blind for any TLS error happening on that domain, when exempted.

To add that behavior, we would need to patch the Endless code.

@mtigas, I assume, jcs didn't implement this on purpose due to security concerns. If he doesn't accept a patch, do you want to diverge further from Endless? 
This would make merging Endless an even bumpier endeavor.

And then there's still the security concern.


Besides: The best way implementing this is probably as follows:

- Create an additional flag "Ignore TLS Errors" for host settings. 
- Default is of course NO and should not be changeable to YES, as that would mean that ALL hosts' TLS errors would be ignored.
- When a user stumbles on a page with a TLS error, the alert will have an additional button to allow an exemption.
- When the user presses that, a new host setting is created for that specific domain, where the "Ignore TLS Errors" flag is set to YES, which then *can* be edited.

**Comment by tladesignz** [comment]
Just had a video call with @mtigas. It was decided, that we want to provide that for people wh really know what they're doing (e.g. running their own onion service with self-signed certs.)

However, there needs to be an additional global switch, which enables this in the first place. Without that switch on, the user won't get the option to override at all.

**Comment by tladesignz** [comment]
Fixed with commit e6fbbd2141139f08023f6699fa32af716f3ffaaf.
