### ISSUE TITLE
Moat: automatically fetch obfs4 bridges for users (via meek or other band)

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#124]
Having OnionBrowser fetch obfs4 bridges for users using the meek/meek-lite pluggable transport, **Large** adversaries "China" may block the bundled obfs4 bridges.

Torproject just aded this feature into tor-launcher [here ](https://gitweb.torproject.org/tor-launcher.git/commit/?id=e921bb15681ac54c9e937b564d31a2a6ec2ceb33)
Here is a photo of the auto bridge fetch in TorBrowser, download the latest nightly with this feature [here](https://nightlies.tbb.torproject.org/tor-browser-builds/2018-03-04/nightly-osx-x86_64/TorBrowser-tbb-nightly-osx64_en-US.dmg)
<img width="605" alt="bridge" src="https://user-images.githubusercontent.com/10781882/37010068-94596482-209e-11e8-8f24-1066a08fc370.png">

**Comment by mtigas** [comment]
Have just spoken to a few folks from the Tor Meeting this week, and we definitely want to do something like this.

(This is the Tor Browser "**moat**" project, which talks to bridgedb via meek to get working obfs4 bridges. Re: https://trac.torproject.org/projects/tor/ticket/22871 & https://trac.torproject.org/projects/tor/ticket/23136 & etc.)

No timeline yet, as we'll probably want to look at TBB's implementation first and figure out the best way to proceed.

**Comment by Baccount** [comment]
Excellent, thank you very much.

**Comment by tladesignz** [comment]
Ok, the MOAT API is described here:
https://github.com/isislovecruft/bridgedb/tree/fix/22871#accessing-the-moat-interface

However, the actual server to ask is missing.
@mtigas Any hint on where to start looking to shortcut this?

**Comment by tladesignz** [comment]
Is one of these addresses mentioned here the MOAT service?

https://trac.torproject.org/projects/tor/ticket/27469

**Comment by tladesignz** [comment]
![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-03-23 at 16 26 23](https://user-images.githubusercontent.com/117089/77332996-17467d80-6d23-11ea-8f48-b68f3ba80244.png)

**Comment by kckthx** [comment]
Thanks @tladesignz so this would come from the "bridge configuration" screen with an option to "request bridges"?

Would they immediately have the bridge after requested, or would it take them to a site like the qr code does?

**Comment by tladesignz** [comment]
> Thanks @tladesignz so this would come from the "bridge configuration" screen with an option to "request bridges"?

Here's a screenshot of the "Bridge Configuration" scene before:

![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-03-23 at 17 03 35](https://user-images.githubusercontent.com/117089/77336779-4ad7d680-6d28-11ea-97b8-ffba4a44e246.png)


I added a button outside the radio list, because the received bridges will be set as "Custom Bridges", if successful.

> Would they immediately have the bridge after requested, or would it take them to a site like the qr code does?

It's 2 steps:

1. Press "Request Bridges from torproject.org" button.
  -> The "Request Bridges" scene opens and a spinner is shown until we receive the CAPTCHA.

2. When CAPTCHA is ready, user can enter the solution and press the "Request Bridges" button, or press the reload button in the top right to receive another CAPTCHA.
  -> A spinner is shown again. When successful, scene is left. Received bridges are stored as "Custom Bridges", therefore checkbox is on that item.

If any error happens, an alert is shown instead. User can retry "Request Bridges" or reload the CAPTCHA.

User can always press "Cancel" to go back to the "Bridge Configuration" scene without changing anything.

The received bridges can be inspected in the "Custom Bridges" scene.

**Comment by kckthx** [comment]
great. so this is what I've got. I think what you made is perfect, just worked out the flow here.
![MOAT Bridge Configuration](https://user-images.githubusercontent.com/36669955/77345484-aee7a400-6d02-11ea-928f-aaf336d2964e.jpg)

**Comment by kckthx** [comment]
@tladesignz
