### ISSUE TITLE
Pull in latest Endless changes

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#128]

**Comment by tladesignz** [comment]
https://github.com/jcs/endless/commits/master

**Comment by tladesignz** [comment]
Will fix an issue which is scheduled for 2.2.0, so moved this issue there.

**Comment by tladesignz** [comment]
Hrgl. I pulled the latest Endless code. Works so far. The only thing is: jcs set the minimum iOS version to 11. We're currently at 9. (Amazingly, Apple didn't drop support for that, yet, in Xcode...)

The main reason is, that the latest code uses calls to [`UIView.safeAreaInsets`](https://developer.apple.com/documentation/uikit/uiview/2891103-safeareainsets).

I could work around that, but that would deviate us further from Endless - and it's additional work.

What's our priority here, @mtigas, @DavidMOliver?

**Comment by DavidMOliver** [comment]
As you know Been, I'm out this week. I won't have a chance to look at this
until tonight.

It seems to me it's a concern to require too-new a release if iOS. In the
geographies we want to serve, do we have good info on release levels used?

Mike us this something we can discover on the store console? If so it would
be great if I could get console access to review this info.

Is there another option, to replace Endless later in our release cycle with
something that accommodates more releases? Or is it better to work-around
the current code base? If the latter, have we done enough mods to Endless
to just call it our own now?

**Comment by DavidMOliver** [comment]
Privately, I see that issue #128 is in activity 3, to be started 2 months
from now. Is the reason you're addressing this now due to using the #128
fix to also fix issues in activity 1?

Perhaps you've not been too heavily involved with the contracting aspects
of work for OTF, but to advise, the timing and positioning of issues and
activities is fixed as part of our contract with OTF. Our payment for these
services is based on that. We're paid for activities, in the order we gave.

Same us true for releases. Because they generate side activities and more
bugs, and because you need to stay focused on the activities as defined,
we'll release as defined.

Now if it's true that, under Mike's guidance, we discover that addressing a
future work item will fix current-activity issues, then we have to document
that as a plan change and defend it in our monthly report to OTF.

All good?

**Comment by mtigas** [comment]
> In the geographies we want to serve, do we have good info on release levels used? Mike us this something we can discover on the store console? If so it would be great if I could get console access to review this info.

Hey @DavidMOliver , just invited your GP email to the App Store Connect panel. (LMK if you'd prefer an invite to a different email.) You should have access to the "Analytics" and "Sales and Trends" sections.

Gonna send an email to the list with some detailed CSVs I pulled out with some calculated totals, but here's a couple summary numbers. These are % of active sessions (* for users who have not [turned off analytics "share with developers"](https://support.apple.com/en-us/HT202100) in system settings):

Worldwide over the past 30 days (741k sessions):
iOS 8-10 - 2.98%
iOS 11+  - 97.02%

Latin America / Caribbean, past 30 days (15.6k sessions):
iOS 8-10 - 2.97%
iOS 11+ - 97.03%

Africa / Middle East / India, past 30 days (9.2k sessions):
iOS 8-10 - 3.03%
iOS 11+ - 96.97%

So my gut is that going up to iOS 11+ won't hurt too much? (In the exported data I'll share, I've got some specific country pull-outs for Brazil, Venezuela, and Vietnam. They closely follow the pattern you see above.)

> Is there another option, to replace Endless later in our release cycle with something that accommodates more releases? Or is it better to work-around the current code base? If the latter, have we done enough mods to Endless to just call it our own now?

Not sure if we want to maintain our own fork of Endless in full, since I do believe maintaining the rest of the browser UI stack is out of scope. I guess the problem here vs other platforms is that we don't have something like Firefox (with LTS releases and such) that is compatible with how we integrate tor (with the older UIWebView framework, since the newer ones don't allow us to do Tor at this moment). I'd prefer to stick with Endless.

**Comment by tladesignz** [comment]
@DavidMOliver, are you sure you want to discuss funding related stuff in the public? Please note, that I had to renumber milestones, because we already released a 2.1.0. So milestone 2.3.0 is actually activity 2.

Besides that, are you really telling me, that we don't fix stuff, because that's not in the order we agreed on before? Because things never change and OTF likes micromanagement? Are you kidding me?

I second @mtigas in staying with Endless. There's no use in changing UI again. Please note though, that, currently, the dependency on iOS 11 is small and rather unnecessary. I could rework the parts and send jcs a pull request. Which he hopefully will accept, so there's a possibility we don't even diverge. 

Not sure, however, how valuable these 3% are. I'd like to think, that the people owning such an old device are poorer than others and poor means vulnerable, so they need our protection the most, maybe?

**Comment by ingfabby** [comment]
@mtigas Hey Mike, I didn't get the invitation to the Apple store panel, could you please add me to it?
fabiola@guardianproject.info

**Comment by tladesignz** [comment]
Removing off-topic comments.

**Comment by tladesignz** [comment]
I fixed Endless and created a pull request to restore support of iOS 9:
https://github.com/jcs/endless/pull/72

I hope, jcs will accept.

**Comment by tladesignz** [comment]
Here's the reply. Ouch.

> The last update to iOS 9 was in 2016. I think it's dangerous to tell your users it's ok to run such an old, unsupported OS, especially in a security-focused application accessing whatever spooky shit is on Onion services.
> 
> There's a ton of stuff in WebKit, its image parsing libraries, the Javascript engine, etc. that Endless (and OnionBrowser) is helpless to protect, so it relies on all of that stuff being updated by Apple.
> 
> Recent commits regarding choosing TLS ciphers is something that Endless doesn't have any major part in supporting, but it relies on iOS being updated to support those ciphers.

Totally lost track of that aspect. He's quite right, actually.

We need to remove support for older iOS out of security concerns alone.

I don't like it at all, but we actually can't help the most vulnerable people with old phones out there.

@mtigas What's your take on this?

**Comment by tladesignz** [comment]
Fixed by latest merge.
