### ISSUE TITLE
Integration with Cloudflare’s captcha token identity system.

### ISSUE THREAD

**Issue by DavidMOliver** [OnionBrowser/iOS-OnionBrowser#145]
Work with CloudFlare "challenge bypass" specification (eliminate CloudFlare Captcha)

https://github.com/cloudflare/challenge-bypass-specification

(moving this item from proposal objective to proposal activity - "stretch" - in activity 2.9

**Comment by tladesignz** [comment]
Unfortunately, it seems to me that this never moved out of draft state. Last commits are 3 years old. Can't find anything relevant on the net regarding "Cloudflare Challenge Bypass".

Instead, it looks like, as if Cloudflare has gone the Alt-Svc route:

https://blog.cloudflare.com/cloudflare-onion-service/

Which makes a lot of sense. We have an issue for that already: #148 
Which turned out to be unimplementable on iOS, because we can't control the `Host` header. iOS doesn't accept changes to that.

**Comment by m4mb01t4l14n0** [comment]
closed without fix. See #148
