### ISSUE TITLE
Support import bridge by QR from photo library

### ISSUE THREAD

**Issue by joxl** [OnionBrowser/iOS-OnionBrowser#146]
When trying to get new (custom) bridges at bridges.torproject.org, you can choose to copy the raw text, or view a QR code. Copying the text proves to be *very* challenging from a mobile OS (tried Safari, Chrome, DuckDuckGo, and even Onion Browser -- using iOS 10.x) with mixed results. Taking a screenshot (or downloading image) of the QR code would be much easier. However, the custom bridges config only supports the live camera. It would be very convenient to be able to choose a QR image from my mobile photo library.

**Comment by eighthave** [comment]
We're trying to define standard URI formats for this kind of thing: https://trac.torproject.org/projects/tor/ticket/15035

**Comment by tladesignz** [comment]
I agree, that would be nice to have! Could be good as a replacement for #124, which turns out to be more and more unfulfillable, because Meek is probably going away, unless somebody comes up with a greet idea.

**Comment by joxl** [comment]
> We're trying to define standard URI formats for this kind of thing: https://trac.torproject.org/projects/tor/ticket/15035

Just out of curiosity, what are the current URI formats supported but the existing (live camera) QR reader?  I just assumed that if a live camera could do it, scanning an existing photo would use the same mechanism.  Although reading the [Trac ticket](https://trac.torproject.org/projects/tor/ticket/15035), it does seem like the URI format needs improved.

**Comment by tladesignz** [comment]
There's currently no URI, it's just a text mode QR code, with a JSON array in it. @eighthave mentioned the URI topic, so we would check on it, bevore implementing this feature. Because, if that would be done, we could forget about importing images and instead register as a handler for that custom URI.

**Comment by eighthave** [comment]
let's take this opportunity to nail down a URI format that works
everywhere.  There are so many useful way to distribute them, I think
this approach will really pay off.

One tricky thing is making the URI clickable in as many places as
possible.  That pretty much means using an http:// or https:// URI.
@n8fr8 & Co did nice work for https://zom.im for a URI format there. For
bridges, we could use something like https://torproject.org/#bridge=foo

Or maybe it makes sense to define two URI formats:

* https:// for sending via messages, etc. so they are clickable
* bridge:foo for cases where the software handling them knows
  what it is handling, e.g. QR code read by a scanner built into
  a tor-enabled browser

**Comment by n8fr8** [comment]
I swear we had incorporated the format mentioned in the https://trac.torproject.org/projects/tor/ticket/15035 ticket somewhere. I think if you do the email request for bridges, it might include those? Otherwise, I do know with Orbot, we allow sharing of your own bridge configuration to a friend.

Anyhow, I like the proposal above for a format that brings up a useful page in case there is no suitable client installed. Of course, any change here would have to be supported by the bridges.tpo team.

**Comment by tladesignz** [comment]
So, nothing has happened with the format in over a year.

I have implemented reading a QR code from an image in the photo library, finally:

https://github.com/guardianproject/poe/commit/452cacdd5c5528ed23efe98c98428e04fc408d95

Will be contained in the next release.

If anything happens with the standard URI, please open a new issue!

**Comment by eighthave** [comment]
7 months ago, I worked out the possible schemes for one-bridge URLs, it is mapped out in the issue linked here, with example code and docs:
https://trac.torproject.org/projects/tor/ticket/15035#comment:11
