### ISSUE TITLE
OnionBrowser home page does an excellent job of making OB seem like AbandonWare

### ISSUE THREAD

**Issue by MarkCallow** [OnionBrowser/iOS-OnionBrowser#149]
The OB homepage (https://onionbr5zulufnuj.onion), 7 _months_ after the fact, still has a message dated Feb 9, 2018 reporting a critical issue with WebRTC and iOS 11 saying a "mitigation will be released in the coming days". Not only has 7 _months_ passed without mitigation but iOS 12 has been released. What is the current status of this issue?

**Comment by tladesignz** [comment]
Yeah, this is unfortunate. Be patient with us, funding is coming in the near future and the homepage will get a refurbish.

Related issue: #117

**Comment by MarkCallow** [comment]
Updating the homepage seems like a simple thing. I assume the real issue is lack of funding to make progress on issue #117. It too has stalled since Feb.

**Comment by mtigas** [comment]
Yeah, sorry. I moved the site over to GIthub Pages recently so that new folks who come on (again, we just got some new funding) can help out with that (vs before, when it was hosted as part of my personal site).

My day job (@propublica) has kind of destroyed any spare time I have for side projects; though I've been lucky enough to have @tladesignz and others come on board during that stretch.

I've been at [a Tor Meeting](https://trac.torproject.org/projects/tor/wiki/org/meetings/2018MexicoCity) this past week and just met one of the folks who may be doing community management (like the website and Patreon) and some project management as part of the new funding. So again, please be patient.

---

#117 is unfixable on our end without some major hacking around the system behavior. WebKit leaks the IPs, and there's no simple way to disable WebRTC -- unlike inline scripts/images, remote fonts, etc, which we've been able to [mitigate with Content-Security-Policy](https://github.com/OnionBrowser/OnionBrowser/blob/f211932ad6ec534096e1c71efe4f339ab784a908/Endless/URLInterceptor.m#L429-L442). No method exists for specifically targeting WebRTC in that way, which is why the only solution right now is for users to disable JavaScript entirely.

(And yes, it's my bad that the site still has old text regarding that. Sorry.)

The #117 webrtc IP leak affects Brave as well, and they've certainly got more people working on that app. https://github.com/brave/browser-ios/issues/1148

Per that thread, the legacy APIs that do leak IP addresses are deprecated and there were some reports 
 that iOS 12 stopped the leaking. (But I have yet to test that. Again. Time.) Unfortunately both of those things won't help folks with devices that can't run newer versions of iOS (and in the case of deprecation, we don't know at what point of the iOS future Apple will actually pull that API so it can no longer be used).

**Comment by MarkCallow** [comment]
OB is still showing the old home page. I suppose you need to make a new release to point it at the GitHub pages home page. I think you should keep this issue open until that's been done.

iOS 12 does seem to fix the problem. See my comment in #117 showing the browserleaks.com WebRTC test output when connected via Onion Browser.
