### ISSUE TITLE
Is this project still open source? Where is 2.1.0?

### ISSUE THREAD

**Issue by synth3** [OnionBrowser/iOS-OnionBrowser#151]
Hi there,

the version (2.1.0) in the app store states that it's an "open source browser" - so where can i find the repo that contains the version 2.1.0? The latest tag I can see here is 2.0.3.

Am I missing something? Can someone please help me?

Cheers,
Andy

**Comment by tladesignz** [comment]
I guess @mtigas forgot to tag or to push his tags... @mtigas could you do that, please?

**Comment by tladesignz** [comment]
...and the project *is* open source. However, you're not allowed to redistribute on the app store in binary form!

BTW: I tagged the latest commit now with "v2.2.0" as this is most probably going to be released soon. So you want to take that for your own research...

**Comment by mtigas** [comment]
@synth3 yep, there is still active development on this app, and all work is open source. you can view this year's roadmap here: https://github.com/OnionBrowser/OnionBrowser/projects/2 you can generally see [the commit log](https://github.com/OnionBrowser/OnionBrowser/commits/2.X) to see how much activity has been going on. (yes, last year was very very quiet.)

as @tladesignz mentioned, the app that we take our browser UI from (Endless) has some license terms that mean you cannot legally distribute binaries of the app unless you get permission from the Endless author.

* https://github.com/mtigas/OnionBrowser/blob/2.X/LICENSE#L1-L7
* https://github.com/mtigas/OnionBrowser/blob/2.X/LICENSE#L27-L29

anyway. @tladesignz I've tagged a 2.1.0 and the most recent testflight build. for now, i've changed your `v2.2.0` tag to be `v2.2.0-rc.1` (we later also tag the same commit with `v2.2.0` if it turns out that's our final 2.2.0 build), just to be extra [semantic](https://semver.org) about it. :)

* https://github.com/OnionBrowser/OnionBrowser/releases
