### ISSUE TITLE
Devices with a notch are not supported properly

### ISSUE THREAD

**Issue by basebandlove** [OnionBrowser/iOS-OnionBrowser#162]
On devices that have the notch such as the X and newer the application doesn’t have proper support. The UI by default looks perfect but the main issue is when there is any sort of popup where the notch is (such as select/copy/paste) in the URL bar is inaccessible/blocked by the notch. This makes using the top URL bar very hard to use. You can reproduce these issues using any notch simulator.

The secouns issue is when you switch the url bar to the bottom - the UI does not properly support rounding so instead of properly rounding and having the buttons in the right location the device just rounds over them cutting them off.

I’m sorry I don’t know anything about iOS UI or I would fix it myself. I tried to investigate but it seems to have to so with safe edge space... again I appologozie I couldn’t contribute more.

**Comment by tladesignz** [comment]
As per your comment on #128:

> This fixes the bottom but not the top.

So you'll get a partial fix with release 2.2.0. I'll move this to 2.3.0 for finishing.

**Comment by tladesignz** [comment]
So, I found one bug with the latest release, where the address field is under the notch after tapping "Report a bug".

Everything else looks fine to me, though. Could you please test with the latest release 2.2.0, which is available since a few days?

If you manage to achieve a situation, where the UI breaks on iPhone X, could you please post a screenshot along with a description of how you ended up there?

That would help a lot!

Thanks for your efforts, and don't worry about your lacking iOS skills... ;-)

**Comment by tladesignz** [comment]
Just recognized: iPhone X in landscape doesn't look as great...

**Comment by tladesignz** [comment]
Will be fixed with #210
