### ISSUE TITLE
Still get the "Can't connect to Tor: Quit App?" dialog even though not necessary

### ISSUE THREAD

**Issue by n8fr8** [OnionBrowser/iOS-OnionBrowser#177]
With build 2.2.0 (20677.510639058), every once and awhile I get the big ugly dialog about losing the connection to Tor, and the prompt of "Ok" or "Quit App".

If I hit, "ok" and just try to resume using the app, it seems to still be connected to Tor, and I can access sites, even onions, without problem.

Can we remove that unnecessary dialog?

**Comment by tladesignz** [comment]
I left it in the code, because it still could be, that we can't reconnect.

For an unknown reason, we can't read the answers on the control port after restart, so there's currently no way to recognize that situation and help the user recover (like re-initing Tor).

I guess, if you're too fast with continuing surfing after restart, you'll see that alert?

**Comment by tladesignz** [comment]
Actually, it was removed I recognized recently. If still there, should be gone in the next version.
