### ISSUE TITLE
Disabling JavaScript on pages disables internally used evaluations

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#196]
When setting content policy to "strict (no JavaScript, video, etc.)", internally used calls to evaluate something on a page are also disabled.

We use the [stringByEvaluatingJavaScriptFromString](https://developer.apple.com/documentation/uikit/uiwebview/1617963-stringbyevaluatingjavascriptfrom?language=objc) call quite often, e.g. here:

https://github.com/OnionBrowser/OnionBrowser/blob/cbe6e61c1d3eac1c9084d82eee20f19290434ddf/Endless/WebViewTab.m#L919-L941

I played around with the content security header and couldn't even find a configuration, which allowed the `stringByEvaluatingJavaScriptFromString` call again... Despite that, it would be dubious anyway, to allow `script-src 'unsafe-inline'` or similar. 

What to do here? @mtigas, any opinions, ideas?

**Comment by mtigas** [comment]
Ooof. This one seems kind of impossible to tackle since _all_ of it (not just the coordinate calculations) require executing JS on the page.

In terms of the first part, I think we _might_ be able to calculate / end up with `CGPoint tapOnPage = CGPointMake(tap.x * ratio, tap.y * ratio);` via some method that doesn't involve JS (like, maybe get `ratio` from CSS or something in `UIWebView` or some calculation).

But ` [[self webView] stringByEvaluatingJavaScriptFromString:[NSString stringWithFormat:@"JSON.stringify(__endless.elementsAtPoint(%li, %li));", (long)tapOnPage.x, (long)tapOnPage.y]];` presents a problem b/c I guess that (or something like it?) is the only way we can actually get to what's visible on a specific point of the page, from Objective-C/Swift.

Maybe we just document / warn the user that this disables the tap-and-hold functionality for saving things?

(Might also be worth checking with Brave or Firefox or Firefox Focus to see if any of them have 1) a "block JS mode" and 2) have to work around it to save images/etc.)

**Comment by tladesignz** [comment]
I seriously jumped into this whole CSP thing and completely rewrote our code there.
I did it "right" this time: https://github.com/tladesignz/CSPHeader
And I think I nailed the problem of how to run our script but no other.
