### ISSUE TITLE
Update default OBFS4 bridges on build

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#205]
There's a source of truth for current default OBFS4 bridges:

https://trac.torproject.org/projects/tor/wiki/doc/TorBrowser/DefaultBridges

Here is a file which is updated from that in time, which seems more easily parsable:

https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/tor-browser/Bundle-Data/PTConfigs/bridge_prefs.js

We should have a script which reads that and integrate that in OB to use before new releases.

**Comment by mtigas** [comment]
Looks good to me.

#224 is related: I took out `OnionManager.obfs4BridgesIPv6` since the only bridge in that array was offlined recently (and removed from that bridge list you're parsing out). Also removes `meek-amazon`. (I'd be more hesitant to just do that & change users' bridge configs if you were using that bridge... But meek-amazon has been offline since the middle of 2018.) Bridge config looking pretty clean now.

(I'm cool with keeping meek-azure hard-coded since the meek bridges aren't supposed to change at all. Any change to that one would possibly need string changes anyway.)
