### ISSUE TITLE
Accept only strong ciphers 

### ISSUE THREAD

**Issue by Nurmagoz** [OnionBrowser/iOS-OnionBrowser#207]
Testing onionbrowser with SSL Labs "SSL Client Test": 

https://www.ssllabs.com/ssltest/viewMyClient.html

There will be shown the browser accept weak ciphers.

plus there is no session tickets.

**Comment by tladesignz** [comment]
Hey @TNTBOMBOM, thanks for the comment.

Currently, I'm working on a bigger change because of #178, where that part which meddled with the TLS cipher list will get dropped, anyway, which obviously seems to be not working anymore.

Since we're only supporting iOS 11 and up now, we will stick with the system's default for now, as long as there's not popping up an important security concern.

**Comment by tladesignz** [comment]
Just revisited this. Since we're using iOS' TLS stack, it's no surprise we're on par with Safari iOS (and MacOS). I currently don't see any hard reason to invest time and money to change any of this, as we would also lose compatibility.

If there are good reasons to do so, feel free to reopen, but prepare arguments and expected outcome.
