### ISSUE TITLE
Onboarding Views

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#212]
Here's the initial prototype for the onboarding flow. 
@tladesignz 

https://invis.io/QEU4SWLC496

**Comment by mtigas** [comment]
Open questions that I've gathered from our meeting this morning. (My own comments in {} )

- Gradient. How do we handle it on various screen sizes?

- Bridge settings: needs to actually just be a native iOS settings page. We already have this. {I think this is an attempt to style that, but is just in conflict with how we currently do it, in a table view?}
  - Further questions (not specific to this ticket): This probably belongs under the "Onion icon" in the UI, but we probably need to work out what all needs to live under that, figure out what is realistic under that spot, and then cement what we're going to have in there.
  - {Many more things about bridges; I will double back around with another proposal on this.}
- Security Levels: overall good, some of the features need to change since we weren't sure about some when the text was written (i.e. WebRTC is not a thing that we can fix)
  - {I'll need to take the lead on any text changes here.}
- Final view (default homepage): Let's maybe not do the "Firefox Focus"-style thing that is fully integrated with the address bar. But yes, default homepage should be MUCH more minimal / less imposing; see also Tor Browser Desktop with their page that occasionally contains messaging. The middle of this page is literally just the default homepage; possibly adding some feature that shows bookmarks or something.

---

My current to-dos: propose some changes to the bridges mockups, updates to security level text.

**Comment by mtigas** [comment]
Wall of text incoming I AM SO SORRY in advance. Thank you all for putting up with me (and for putting up with all the really awful, highly-technical twists and turns along the way).

---

**Splash / "Connect To Tor"**

I think consensus was to sort of merge Screen 1 (splash screen) and Screen 2 ("Connect to Tor" screen).

(Aside: For the splash screen (the static one that we can't localize/etc): **Maybe let's just do a text-less rendition of what we've got here (just the gradient background).** Since that's what'd show up for the split second before you're either going into Screen 2 _or_ into the "Connecting..." loading screen, and showing words/icons on it is bad b/c you probably don't have time to read it. Willing to defer to literally everyone else on this though.)

Background:
* I think @tladesignz wanted some definition on what the background & what the things render like on non-phone screens.
* Color: "Circular gradient starting from top left at this (lighter purple color) outward to (darker purple color) by about 200px". Something like that.
* Background icon thing: Guess this is just an SVG of the "donut" icon that'll float behind where we have the text, anchored on the left-edge of where the text starts to render.
* Text: Where does this go if this is rendered on an iPad (or anything larger than phone)
* Color & text placement probably applies to all the things in the onboarding; later views won't have the icon.

Our current version has something like "Sometimes you need a bridge to get to Tor" on the screen where you decide between using a bridge or connecting without. I think we need something _like_ this on this screen. I just noticed that newer versions of Tor Browser use this language, which isn't _too_ bad: [screenshot here](https://tb-manual.torproject.org/static/images/configure.png)

(Docs here https://tb-manual.torproject.org/running-tor-browser/ )

Like the _primary_ reason this page exists is because a user has to decide whether they need bridges or not.

How about:

> # Explore the web freely.
> No tracking. No censorship.
>
> If you are in a country or using a connection that censors Tor, you might need to use a bridge.
>
> Connect to Tor
> Use a Bridge

---

**Bridge Configuration**

(I'm going to imagine that the Bridges screen in the mockup doesn't have the "Done" button at the top-right, since all of the options here are either a "do this & then start connecting", or "go to next screen and then connect after that.)

This will literally be the same screen that we show people if they need to edit bridges later; so unfortunately, it will either look out of place _here_ or it will look out of place _there, in the "Onion icon" settings_. My inclination is to design it as if it were in settings, like the current way that the page works. It also makes more sense to me as a radio select rather than a list of links. 

I'm not sure what is easily doable from from the dev perspective, but I think this is mostly just a matter of cleaning up copy and re-styling the table of four options. The main question is: is it possible to make it consistent with how other settings look (the things under the "Gear" icon, under the "Shield" icon, etc. -- standard-looking iOS settings pages) while also making it not jarring as part of the onboarding? If there isn't, again, I'd lean toward looking like a regular settings view.

<a href="https://user-images.githubusercontent.com/53129/70102603-9eea6e00-1606-11ea-809a-baf2963d5edc.png"><img src="https://user-images.githubusercontent.com/53129/70102603-9eea6e00-1606-11ea-809a-baf2963d5edc.png" width=200></a>

Perhaps copy should be updated to something more like:

> ("Done" option in the top-right)
>
> # Bridges
> If you live in a country that censors Tor, or if you are using a connection that blocks Tor, you can try using bridges to connect. obfs4 makes traffic appear "random," and meek-azure makes your traffic pose as traffic to a Microsoft website. If one type of bridge does not work, try using a different one.
> 
> - [X] No bridges
> - [ ] Built-in obfs4
> - [ ] Built-in meek-azure
> - [ ] Custom bridges

Not literally with checkmarks, but I'm just putting them in there to help describe what I'm thinking conceptually. (The current app puts the checkmark on the right-hand side.)

The fourth option, as we currently have, is a menu item that brings you to another page -- the one where you paste in the custom lines. So sure, that one acts kind of like a link. But after finishing that view, the "check mark" for the selection moves down to the "Custom bridges" option, since now that's the one that is set out of the four.

I am inclined to leave "Custom bridges" without further description in this screen unless @n8fr8 thinks we should talk about it. (The argument here is that the built-in bridges often get blocked because it's a known list, versus the random custom bridges you would get by visiting `bridges.torproject.org` or emailing `bridges@torproject.org`). 

---

**Custom Bridges**

Can we just keep the current view? Text documentation above (with link to `https://bridges.torproject.org/`) and text input at the bottom. This is already a page that only very advanced users (or users with very special anti-censorship/anti-blocking needs) will need to see, and therefore I really don't think we should wring our hands much more. Again, if there's a way to make this page not-jarring (while making it "fit" with settings pages across the app) then let's do that.

<a href="https://user-images.githubusercontent.com/53129/70103152-45833e80-1608-11ea-99a4-209708e5d16b.png"><img src="https://user-images.githubusercontent.com/53129/70103152-45833e80-1608-11ea-99a4-209708e5d16b.png" width=200></a>

Tor now uses obfs4 as the default, so the text could probably look like this now:

> In another browser, visit https://bridges.torproject.org/ and select "Get Bridges". You do not need to configure advanced options. You can copy-and-paste the text you get, or you can save the QR code image and use the "camera" icon at the top-right to load bridges from the saved image.
>
> Alternatively, send an empty email to bridges@torproject.org -- this only works if you are using Gmail or Riseup for email.

(When clicking the `https://bridges.torproject.org/` link, we should present a popup warning "This will open the Tor Bridges site in Safari; this will not be anonymized over Tor." -- with OK / Cancel. Or something like that.)

---

I'll come back to **Security Settings** and the rest tomorrow. (Generally, my thoughts are as in the earlier comment. UI is good, I think I need to rewrite some of the text for each "level". Assuming the "final" screen is the app on the default homepage, let's drop the Firefox Focus-style custom address bar and work on the default homepage as it's own web page thing and not literally an integral part of the POE onboarding bits; keep the look & feel, but we'll implement it as a web page.)

**Comment by kckthx** [comment]
Hi @mtigas thanks for putting this together! Below are some of my responses to your update. 

Splash/connect

* As far as the words on the loading screens (assuming you’re speaking of the ones with animals on them, if not I may be way off here), we let this copy be about ways people use tor. I know that it could possibly be going really fast, but it also might not. haha. That’s one of the reasons this isn’t necessarily vital information to how to technically use it, just situationally. 
* What mike said about the splash screen ui is correct. SVG icon stays glued to the left. I can also provide a large image to scale on all devices if that works easier.
    * Why could they not have the icon? If I gave a still image would this be a work around? It would only be needed for the first “real” screen (after splash).
* I do like having copy that explains a little bit more about configuring and what a bridge is used for at the front. The rest of the team over here is currently working on messaging overall for Onion Browser so the “Explore the Web Freely” is likely to change, but we can still use the line about “warning” the user about if they need a bridge.

Bridge Configuration

* I’m on board with making this view standard to iOS ui and agree about radio selection, and am going to start working on this design.
* One of my biggest concerns with having URLs in line with the text, especially when they’re surrounded by information about how to safely open them, is that some people may just see a link and click it without reading around. I would like to do some work around if there is another standard iOS way to handle a link without it being inline with body copy. — this could also maybe keep us from having to do an alert? 
    * we could write out the url in line, but not make it live, and have a button at the bottom, etc.

**Comment by kckthx** [comment]
Oh, another question @mtigas and @tladesignz 
Would the "Bridge Configuration" settings view also live in the global settings menu (gear icon), or would it only live in onboarding and under the onion icon?

**Comment by kckthx** [comment]
Also, just had another thought while working out these views, if on the first screen in onboarding (after splash) we use the language "Bridge Configuration" or "Configure Bridges" instead of  "Use a Bridge" it may be less jarring when they see a settings page pop up.

**Comment by mtigas** [comment]
(Updated prototype that was linked in chat: https://projects.invisionapp.com/share/R2V4M7IMUWV#/screens ; @kckthx I think you worked on this after you'd commented here, so my replies here are sort of in response to that as well.)


> As far as the words on the loading screens (assuming you’re speaking of the ones with animals on them, if not I may be way off here), we let this copy be about ways people use tor.

Ah! I was actually only referring to the very very first "Onion Browser / Your trusted connection to Tor." screen that didn't have any actions on it. (Looks like it has been rolled into the following screen in the new prototype, so 👍  )

> One of my biggest concerns with having URLs in line with the text, especially when they’re surrounded by information about how to safely open them, is that some people may just see a link and click it without reading around. I would like to do some work around if there is another standard iOS way to handle a link without it being inline with body copy. — this could also maybe keep us from having to do an alert?
> we could write out the url in line, but not make it live, and have a button at the bottom, etc.

In the new prototype, I like where the "Custom Bridge" screen has gone, being split up into those three sections: manually paste, use a QR code, or a button to send off the email.

I think having the URL mentioned there + the ability to copy the URL to clipboard is maybe the best way of handling all that? (Also if someone wants to just use some other, non-Safari, browser to visit the Tor Bridges page.)

I'd probably change the page/menu item to be "Use Custom Bridges" (instead of "Add Custom Bridge"). When you visit the Tor Bridges page, scan a QR code, or get the email response, I think it always gives you three lines; the user should paste all of them in here, so I think we should always use the plural here.

> Would the "Bridge Configuration" settings view also live in the global settings menu (gear icon), or would it only live in onboarding and under the onion icon?

I think only onboarding and onion icon, maybe.

We might need to put something in the global settings menu that says "Tor Connection settings can be found under the Onion icon". Or something like that.

> if on the first screen in onboarding (after splash) we use the language "Bridge Configuration" or "Configure Bridges" instead of "Use a Bridge" it may be less jarring when they see a settings page pop up.

Agreed! "Configure Bridges" maybe? But yes; I like the slight signaling that you might encounter some settings.

I think most or all of my concerns about those bridge bits (and making the "actionable" screen the first one) are handled well here, at least in terms of structure. I assume that we'll also keep the Security Level bits from the prior prototype too?

(I'm also assuming that we'll have to tweak the wording at least a couple more times as we move on, but again — structure and design are looking great IMO.)

Not sure about the image format bits (for logo or background) and what's most useful. @tladesignz should comment regarding that, and also if he's noticed something that I haven't.

Thank you!

**Comment by kckthx** [comment]
Awesome! Thanks for your feedback.
just to clarify though, when referring to using the plural for bridges --
-- is this what you were referring to @tladesignz that we can't choose between any of them? I thought that all of the code was one bridge.

**Comment by kckthx** [comment]
This is the most updated prototype we have @tladesignz @mtigas there's now a static screen to tap into to begin onboarding. The copy changed on the first screen with acctions "Connect to Tor" but everything else is the same as above

https://invis.io/WTV5ZQ376ZB

**Comment by tladesignz** [comment]
@kckthx I have some questions/needs:

1. I would need the background. Can you please provide an SVG containing the ring and the gradient background? Please work with the iPad 13" as target size (a quadrat of the longer side, so target size should be 2732px x 2732px) and tell me how to position on smaller devices (e.g. attach to top/left or center/center) and scale (e.g. always 1:1 and things cut off or scale to bigger side)

2. Is the wording final? If not, please provide it!

3. The last discussion's result was, that we need an introduction to the security levels. How do we go about it? Should I just open them immediately after the first start? Want to do an extra scene?

4. The help text for the security levels is still missing. You defined a button which should lead there on your mockups, but I didn't have text, so I hid the button. We could/should also work with that. e.g. reuse that text in a first-time interstitial scene to explain security levels or show the explanation right at the end of the security level popup. Maybe only on first show.

**Comment by kckthx** [comment]
@tladesignz 

1. I'm attaching the svg of the background -- the image should stay positioned to the center and left and should reduce size proportionately -- obviously the dimensions are different for the phones, so the left side extra would cut off. As far as the text goes, the ratio of the margins should stay proportionate. Text will scale.
[OB_DEL-ON-Background-2020-1-09.svg.zip](https://github.com/OnionBrowser/OnionBrowser/files/4041666/OB_DEL-ON-Background-2020-1-09.svg.zip)
 
2. As far as the screens without technical language (about the bridges or security level) the language is final on our end. I've asked the team to provide any feedback and haven't gotten any so I would say keep it. 

3-4. I posted a prototype in the riot channel, and I will repost here as well -- after connecting to the Tor Network, the "next" button takes the user to the security setting. Not sure what you mean about "help text" -- @mtigas mentioned having a go at this copy to make sure it's accurate.
https://invis.io/FKVG7QG98JN

**Comment by tladesignz** [comment]
@kckthx, sorry to bother you again:
Turns out having the ring and the background all in one needs an awful hack which I also cannot use in the splash screen.

Can you provide the cut-off ring and the gradient background as two files please? Thanks a lot!

**Comment by kckthx** [comment]
[OB_DEL-ON-2019-01-13.zip](https://github.com/OnionBrowser/OnionBrowser/files/4054075/OB_DEL-ON-2019-01-13.zip)
 @tladesignz
