### ISSUE TITLE
Onion icon behavior (in navbar)

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#223]
#222: shield icon 
#223: onion icon  
prev settings work is in #211  
onboarding work in #212

**Comment by kckthx** [comment]
@tladesignz @mtigas 

![Onion Menu](https://user-images.githubusercontent.com/36669955/70089088-1a372a00-15dd-11ea-897a-5191eb0e66a8.png)
**WHAT HAPPENS**
- a depiction of the tor circuit -- all the connections.
- the "New Circuit for this Site" would change the circuit information... this was modeled after the desktop Tor Browser---so I'm not completely sure what happens when it's tapped. 
- new bridge will open the bridge configuration

**Comment by tladesignz** [comment]
Get currently used circuit info probably with the `circuit-status-changed` event:
https://torproject.gitlab.io/torspec/control-spec.html#circuit-status-changed
https://torproject.gitlab.io/torspec/control-spec.html#setevents

Resolve node names to IPs:
https://torproject.gitlab.io/torspec/control-spec.html#getinfo
`ns/id/<OR identity>` or `ns/name/<OR nickname>`

Resolve node IPs to countries:
https://torproject.gitlab.io/torspec/control-spec.html#getinfo
`ip-to-country/*`

Should be implemented in `Tor.framework` so more apps can profit from this.
