### ISSUE TITLE
How to get tweetdeck working?

### ISSUE THREAD

**Issue by fk3ma** [OnionBrowser/iOS-OnionBrowser#225]
I have been a paid supporter of this app for several months now. A little disappointed with usability of this product and speed of development. Will continue to support it but many websites do not work reliably even with the most open settings configured. 

I can get twitter to sort of work using the mobile site. Its not reliable sometimes have to continually press reload to get a page to work. 

I can't get tweetdeck to work at all in onion Browser. I have twitter.com, twimg.com and default set to content policy open and allow mixed resources. 

Hopefully other people use tweetdeck could sure any tricks to get it working?

Thank you

**Comment by tladesignz** [comment]
Hey @fk3ma, thanks for notifying us!
That was actually a really bad bug with a component which modifies the Content-Security-Header.

It will be fixed with the next release, which is due for Christmas.

Meanwhile, if you're not on our beta-testing track, please shoot me a personal message, then I can give you a link where you can download our TestFlight versions!

@mtigas: Can you do a new TestFlight build with the latest master (aka. 2.X branch)? This is a major bug which needs fixing.

**Comment by mtigas** [comment]
2.4.0 (47.513620079 ) has been built and pushed over to testflight, with the following commits from master:  
https://github.com/OnionBrowser/OnionBrowser/commits/v2.4.0-testflight-47.513620079

(it's still going through "public test" review, but should be available on testflight shortly)
