### ISSUE TITLE
Consider removing OS version information from User Agent String 

### ISSUE THREAD

**Issue by rocodes** [OnionBrowser/iOS-OnionBrowser#227]
Currently, the UAS is [slightly modified](https://github.com/OnionBrowser/OnionBrowser/blob/81aef72ea44325faf62873119713fe8e01a0eb8a/AppDelegate.m#L418) to report that a user is on Safari, but still includes OS version information and webkit information: 

`"Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4"`

The Tor Browser Android and Tor Browser Desktop approach is to try to make all users (on desktop, on mobile) [report the same information](https://gitweb.torproject.org/tor-browser.git/tree/mobile/android/chrome/content/browser.js?h=tor-browser-60.6.1esr-8.5-1#n3352) to reduce the ability to identify specific users, in line with [their guidelines on fingerprinting](https://2019.www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability).

Would there be any drawbacks to doing something like this for iOS users, as well as reporting a webkit version of xxx+ (instead of the specific webkit version), to avoid exposing further potential identifying information?

**Comment by tladesignz** [comment]
The design goal was to have the user look like regular iOS users, because AFAIK, we can't control the user agent string in all circumstances.
Maybe @mtigas wants to give more background info.

**Comment by lanierband** [comment]
@mtigas can you provide info here so we can close or fix this?  Are we getting UA string from some OS property or something?  Perhaps UIWebView does this "internally" in a way applications can not mess with?  I wonder what WkWebView does, and if this will change when we adopt that library?

**Comment by lanierband** [comment]
Here's instruction on changing UA string in Obj-C for UIWebView: https://stackoverflow.com/questions/478387/change-user-agent-in-uiwebview

Here's instruction to change UA string in WkWebView: https://stackoverflow.com/questions/26994491/set-useragent-in-wkwebview

**Comment by mtigas** [comment]
User agent can be overridden in the main options menu -> Default Security. There is a User Agent text field at the bottom.

Regarding your question about whether it's internal and can't be edited: in testing (years ago) there where some edge cases that still revealed the real user agent (I believe the basic `navigator.UserAgent` in JavaScript is one of them).

The 1.X version of Onion Browser used to provide some pre-set options for faking certain user agents, but rather than completely omit the version (which I think Android Tor does -- which it can, because Firefox Mobile may already omit it on some platforms) I selected a single user agent string (so that regardless of which iOS you were running, you looked like 12.0 or etc). I believe this also ran into issues with many things that sniff user agents (and was also still affected by things that revealed the true useragent).

I'm happy to have us look at this some more in the near future. I think we'd need to figure out:

* What the static fake user-agent string should look like. (And maybe it should be different on iPad since the base iPad User Agent is already different from iPhone and the screen differences do warrant counting it as separate platform?) 
* Re-do some of the old research about what the edge cases are so we're actually convinced this is solid enough to rely on for privacy.

Regarding the second part: I'm fairly sure that simply having JS enabled would be enough to infer the OS version with enough effort. Compared to TBB desktop or Tor Android, we don't implement our own rendering engine or JS engine; it is literally part of the OS (and apps are not allowed to implement a separate browser engine). So the threat/mitigation model is quite a bit different. (So we currently go with "you look like Safari on your current version of iOS" rather than "you essentially look [totally unique](https://panopticlick.eff.org) because the features of the browser engine and the faked user agent don't line up".) It's not such an easy decision.

**Comment by rocodes** [comment]
So, in between when I filed this and now, I did a bit more poking around, and it does seem like the whole user agent on Tor browser situation is a bit of a mess. 
TBB (currently) reports a standard version of Windows / Firefox as the HTTP-user agent, but the `navigator.userAgent` correctly reports the user's platform, spoofing to most common version (so all OSX users on up-to-date browsers report the same version of macOS).  On mobile, it looks like all Android users report the same UAS, unless they request the desktop site. 

I understand the challenges with "trying to look like Safari" vs "trying to look like Tor browser", and I can understand why you'd need to go with the former, @mtigas. I was just wondering if there was any further precise information that was being shared that could be generalized.  (I'm not suggesting to try to report a different OS/platform).  But it sounds like you have already thought of all this and have run up against the limitations of what is possible or even useful! So feel free to close.

**Comment by tladesignz** [comment]
Just for reference, this is what Onion Browser currently does:
https://github.com/OnionBrowser/OnionBrowser/blob/d9f1cd8be0e879df8b79c5f4cb243835fe4c1a6a/OnionBrowser/AppDelegate.swift#L99-L124

And I think this was adopted from Endless. However unclear, what Endless adopted from Onion Browser 1 as I think that was a reference for the Endless development.

I'll close it now, as @rocodes suggests, because I don't think we want to change it at the moment.
