### ISSUE TITLE
App updates using UIWebView as of December 2020 will not be accepted by the App Store

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#231]
> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

https://developer.apple.com/news/?id=12232019b
Will this effect Onionbrowser, because it’s based of the endless browser?
@mtigas 
@tladesignz

**Comment by tladesignz** [comment]
Yes, it will, if we don't come up with a working solution until then.

Either Apple will provide us with a SOCKS interface to `WKWebView` or we need to get Tor run stable inside a Network Extension, which, unfortunately, it currently doesn't. Not so much Tor's fault, but our unstable glue code's (tun2tor). Also, we would probably loose the ability to support OBFS4 and Meek, because we won't be able to cram that into the 15 MB RAM limit of Network Extensions.

You can read more on the technical details here, if you're interested and haven't, yet:
(Note the date of the article - Tor is now very much improved.)

https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

**Comment by tladesignz** [comment]
https://twitter.com/tladesignz/status/1214532167235252224
https://openradar.appspot.com/FB7524212

**Comment by lanierband** [comment]
"The End" by The Doors: https://www.youtube.com/watch?v=VScSEXRwUqQ

At least now we have a definitive date.

**Comment by tladesignz** [comment]
Related: #47

**Comment by tladesignz** [comment]
https://developer.apple.com/news/?id=edwud51q

**Comment by tladesignz** [comment]
Closed. Further progress will be tracked in #47.
