### ISSUE TITLE
reCaptchas can no longer be seen nor solved

### ISSUE THREAD

**Issue by Johandrex** [OnionBrowser/iOS-OnionBrowser#232]
If you go in on a site with google reCaptcha it can no longer be seen nor solved with the latest iOS update, which worked fine before. I've attempted to tweak all of the settings, put the app in insecure mode, disabled all URL blockers and so on. But it never appears to work. If you go on a site with cloudflare/reCaptcha you should be able to see what I'm talking about.

Example: Try accessing myetherwallet.com via the onion browser, won't work. I've seen similar results when visiting a few other websites.

**Comment by tladesignz** [comment]
I'm afraid this is the same as issue #225. It was fixed with commit 31ae84fdca3a8dd0892967b25d82e20b0afe57b6.
Unfortunately, that was too late for the 2.3.0 release.
It will definitely be fixed with release 2.4.0, which is very due.

Meanwhile, I can recommend you to get on our beta channel.

Shoot me a direct message, if you want to get into it!

@mtigas, @m4mb01t4l14n0: We should *really* release 2.4.0!
