### ISSUE TITLE
Create Travis build script for Tor.framework for Tor Project

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#233]
the PLUTO team thinks it's a good starting point toward helping the Tor Project build binaries that are compatible with iOS if we provide them a build script for their Travis build environment.  Here are instructions on doing so from teammate Hans:

- you already have the Tor/*.sh scripts for building the pieces in Tor.framework, so it should be pretty straightforward to put that into a standalone script to be ported to .travis.yml
- just do a script that starts fresh each time
- then use git submodule to init the git smobules
- then use git submodule to set the tor submodule to which ever commit you want to test
- then run the build
- git clone https://github.com/iCepa/Tor.framework.git

...with that xcode command line tool.  This can be viewed as the first in a series of steps we might take going forward.

**Comment by mtigas** [comment]
can we get someone to share us an example of what a travis build looks like for Tor's other stuff? (i.e., what the outputs are once the CI build runs)

There is some ancient stuff [here](https://github.com/OnionBrowser/OnionBrowser/blob/2.X/.travis.yml) that doesn't work anymore (see <https://travis-ci.org/OnionBrowser/OnionBrowser>)  because it's been a long time since I touched it, so the Xcode version and probably other things about the Travis environment are out of date. And that was set up for running some super rudimentary tests, rather than uploading some output/artifact at the end of build. But I think it's a place to start.

**Comment by tladesignz** [comment]
Actually, the requirement is about Tor.framework, not so much Onion Browser. The idea is, that Tor Project does start to compile Tor for iOS, too, so they immediately recognize, when something breaks there and they can fix it themselves with their deep knowledge about Tor, rather than we do it and have to puzzle over why it broke again.

Just recognized, there is already a Travis script:

https://github.com/iCepa/Tor.framework/blob/master/.travis.yml

Need to test, if it still works, however.

**Comment by m4mb01t4l14n0** [comment]
Yes, it seems like it's only for the narrow part of Onion Browser that has the linkage to Tor itself.  Good luck sussing out that Travis script, @tladesignz !

**Comment by tladesignz** [comment]
Ok, so it did work, but with a very old macOS/Xcode image.

I updated it to the latest and fixed the then appearing bugs.

https://github.com/iCepa/Tor.framework/commit/f4c720164c5a3123bfd603d013411d0848a0ca0d
https://github.com/iCepa/Tor.framework/commit/0cf14e01e4fc04e9c86322ae2b047e151adebb32
https://github.com/iCepa/Tor.framework/commit/8fc455b6ad72da62135b2384e6eaa8505daf7672

**Comment by tladesignz** [comment]
https://trac.torproject.org/projects/tor/ticket/33522
