### ISSUE TITLE
Improve tab overview (was: Add toggle for Safari style Tab browser)

### ISSUE THREAD

**Issue by bsprk** [OnionBrowser/iOS-OnionBrowser#239]
![9C9AAE0A-D6FE-4998-8887-FC76EB6CD72A](https://user-images.githubusercontent.com/30192243/72221892-cd078a00-3584-11ea-84ed-b63d9a36f8e6.jpeg)

The current tab browser is too small and makes it difficult to manage tabs on small displays.

**Comment by fluffypony** [comment]
Yeah I'm really not enjoying the new "tiled" tab browser. The previous cover-flow style was MUCH better, and a Safari-style interface would be ideal.

**Comment by tladesignz** [comment]
> Yeah I'm really not enjoying the new "tiled" tab browser. 

Sorry, to hear that. Firefox mobile has that, too, so I thought it would be an inexpensive way to improve the original.

> The previous cover-flow style was MUCH better

I found that horrible, because you could only ever see one tab.

> , and a Safari-style interface would be ideal.

We planned for something like that, but unfortunately, it turned out to be really difficult to implement. Apple must have thrown a ton of money on that feature. Also consider iPad. iPhone style doesn't make a lot of sense on iPad, so there would be a lot of work to accomodate all of this.

But I hear you. I'm not satisfied, yet, with it, too. Improvements, which should to be made are the following:

- X button touch area needs to be bigger and/or swipe tile up to remove page implemented.
- Pages should be zoomed out to show bigger piece of page.
- Layouting of tiles on different screen sizes needs to be improved. Some conditions bear too much spacing between tiles.

Unfortunately, we're running into the end of the budget, so I'm not sure how much of this I can get done until then.

**Comment by m4mb01t4l14n0** [comment]
Perhaps let's add a review of this toward the end of the project.

**Comment by DrHyde** [comment]
> > Yeah I'm really not enjoying the new "tiled" tab browser.
> Sorry, to hear that. Firefox mobile has that, too, so I thought it would be an inexpensive way to improve the original.

I like that, on iPad, except ...

> * X button touch area needs to be bigger and/or swipe tile up to remove page implemented.

Yeah. It's a lottery whether a tab actually closes when I try to hit that X. It closes about a third of the time in the right column, and about a tenth of the time in the left column.

**Comment by tladesignz** [comment]
So, a little improvement went into 2.5.0. I'll move this to the 2.6.0 milestone, so I don't forget.

**Comment by m4mb01t4l14n0** [comment]
Agreed: too much effort for small UX gain, other issues have higher priority, small modifications to our UX to improve UX after initial implementation.
