### ISSUE TITLE
Cannot play videos

### ISSUE THREAD

**Issue by deedeeen** [OnionBrowser/iOS-OnionBrowser#242]
Set the security level as Insecure (1/3), not possible to play videos with play button as placeholder

**Comment by tladesignz** [comment]
Link, or it didn't happen...

Seriously, just tested on https://m.youtube.com/
Works fine for me. Can even switch off WebRTC and mixed-mode content.

Feel free to reopen, *if* you can also provide a link!

**Comment by tladesignz** [comment]
One last thing: Video loading is bypassing Tor, that's why you need to use the "insecure" mode! 
(Unfortunately, that's a constraint in iOS' system design. Videos are played back by another process which we can't proxy.)

Therefore, if you're behind a censor filtering that video, you're out of luck, obviously.
