### ISSUE TITLE
Onion Browser throws error on video blob file download

### ISSUE THREAD

**Issue by Sharpiro** [OnionBrowser/iOS-OnionBrowser#245]
* testing with "Insecure" security level.
* testing with popular [file-saver library](https://www.npmjs.com/package/file-saver)

In safari, when you download a blob with a supported mime type, in this case `video/mp4`, you will receive an option to "View" or "Download" the data.

When trying this in Onion Browser, you instead receive an error, `Error Plug-in handled load blob://..`

Here is an example of the bug that works in every other browser I tested:
https://sharpiro.github.io/bugs/onion-browser/video-download/

Here is the source code:
https://github.com/Sharpiro/bugs/tree/master/onion-browser/video-download

**Comment by tladesignz** [comment]
Hm. Could have to do with the fact, that video is normally not handled by UIWebView directly. Your code also only works when I switch to "insecure".

So, I guess the loaded data does not get where the script wants it, due to our Tor tunneling for some parts of the webpage but not for the video?

**Comment by Sharpiro** [comment]
Yea I did note that it only even gets as far as it does in "insecure" mode.  This is a function that works in Tor Browser "safe" security level, so It should work on Onion Browser's standard security level.

**Comment by tladesignz** [comment]
Yeah, no. This is iOS. A very constrained environment. Onion Browser basically is Safari with a different chrome where parts of it are able to make connections via Tor. There's an update coming, where we explain some limitations a little better.

**Comment by Sharpiro** [comment]
I see. So you don’t think this would be fixable even in insecure mode?

**Comment by tladesignz** [comment]
Well, probably, if we strip all the Tor stuff. But what's the point, then?

See, the way this script seems to handle video downloads, you're downloading the video via a direct connection, side-tracking Tor. So you're leaking your real IP address. And you're hitting a network provider's or country's firewall.
So even if we get it to work, it's still insecure, which begs the question, why are you using Onion Browser in the first place? Just use Safari then, and you're at least aware of the implications to your security.

**Comment by Sharpiro** [comment]
I'm just executing a basic JavaScript fetch to get a file into memory.  In Onion Browser fetch still goes through Tor right?

You could assume that the provided client test code is served over Tor from an Onion Service, then the video download via fetch would also be served over Tor.  That's my use case from which I created this simplified example.

**Comment by tladesignz** [comment]
> I'm just executing a basic JavaScript fetch to get a file into memory. In Onion Browser fetch still goes through Tor right?

Well, yes. But as the error says "Plug-In handled load". It seems, because it is a video file, the Safari plug-in which handles video files still loads it, instead of our UIWebView running inside our app's process.

You can see it in the request header's User-Agent string, which is different from normal requests:
AppleCoreMedia/1.0.0.15F79 (iPhone; U; CPU OS 11_4 like Mac OS X; en_us)

So it doesn't go through Tor. Because AppleCoreMedia is running outside of our app process and there's no API to make AppleCoreMedia use our Tor running inside our app process as a SOCKS proxy.

That's why we say that doing anything with video is insecure.

> You could assume that the provided client test code is served over Tor from an Onion Service, then the video download via fetch would also be served over Tor. That's my use case from which I created this simplified example.

I'm pretty sure the video file wouldn't even be downloaded when you hide it behind an Onion service, because AppleCoreMedia can't connect to that.
But happy, if you prove me wrong, that would be an interesting case.

Can you also try with a non-video file. Like a PDF document, e.g.?

**Comment by Sharpiro** [comment]
Interesting.  I'm fairly knowledgeable about Tor but not IOS intricacies.  

As far as a non-video example, I actually had another one prepared to open as an issue later.  This one however, doesn't throw an error, it instead is just a bit awkward.  Again, works fine in main Tor Browser.

Basically what happens is, instead of being prompted to "View" or "Download" the file, as is the case in Safari, Onion Browser immediately navigates to the blob url as if "View" was selected, and then for some reason opens a new blank tab. 

At the very least, no new tab should be opened for no reason.  But it would be nice to have the "View" and "Download" option to appear like in IOS for flexibility.

ex:
https://sharpiro.github.io/bugs/onion-browser/text-download/
src:
https://github.com/Sharpiro/bugs/blob/master/onion-browser/text-download/index.html

**Comment by tladesignz** [comment]
Oh, man. I debugged this for 4 hours now. I'm sorry, but this library just won't fly with Onion Browser.
It hits so many things we're doing to protect the user that it just won't work.

The empty tab opening is actually an error. So, thanks for pointing me at it.

When I fix that, though, the lib will try to open a `data:` URL in a new tab. And our inter-tab communication is so stripped down, that this won't work. (e.g. `window.open` will return a `FakeWindow` object instead of a real one.) This is partly on purpose and partly because it is actually a real hurdle to hand around JavaScript calls between 2 `UIWebView`s.

The next blocker then is our `NSURLProtocol` implementation, which denies loading `data:` URLs in a `UIWebView`. For some reason, that is then not handled internally in the `UIWebView`. (Which it actually should, I think, but doesn't.)

Finally, it hits our universal-links protection. (An iOS feature which makes e.g. Youtube links directly open in Youtube apps and which we want the user to protect from, since it would leak private info to a censor...)

Then, there's still the original problem with videos not being accessible, because they're not loaded through Tor at all.

Sorry, but if you want to give people stuff to download via Onion Browser on an Onion service, just hand out plain links. And better don't let it be A/V content, because that will bypass Tor.
