### ISSUE TITLE
Finalize security level language

### ISSUE THREAD

**Issue by n8fr8** [OnionBrowser/iOS-OnionBrowser#249]
Is it:

- Insecure / Moderate / Secure

or

- Low / Moderate / Maximum

The website currently shows the 2nd, versus the App shows the 1st option.

Should we match Tor Browser?

- Standard / Safer / Safest?

There is concern that our "Standard" on Tor Browser is not equivalent

Let's find a way to survey, review, wordsmith what we need.

**Comment by n8fr8** [comment]
Let's write a more complete document first to capture everything.

**Comment by tladesignz** [comment]
Please let me know, if/when I should change any language in the app!

**Comment by n8fr8** [comment]
some comments from me

- "Insecure" makes it sound like TLS security is broken potentially, or other basic non-Tor related security features will not function

- Why would a secure browser offer an "insecure" setting at all?

- I agree using the same language as Tor Browser setting levels could be confusing

- "Insecure" is really the "I am aware there are risks, but I just want this site to work"

- Could we add an additional set of explanation the first time the user sets it to the lowest level to explain what this means?

- Can the lowest level be temporary, just for the current domain?

**Comment by n8fr8** [comment]
could we not have summary labels at all, and just slow the slider with descriptive text? Maybe just use 1-2-3 so there is no meaning assigned.

**Comment by cstiens** [comment]
@n8fr8 and @tladesignz I have a question. For the 1st level (currently insecure)—is a user's connection to that website completely insecure? If it's a website with HTTP, there is still a level of security the user has when accessing it, correct?

If so, insecure is misleading to me. 

Second question—What does a user actually (in reality) get at this level? 
* Normal browsing mode (similar to what one would get in a browser like chrome where things aren't tunneled through Tor)
* No link protection. What do I actually get when Universal link protection is on?
* Audio and video may connection through a normal connection rather than being tunneled through Tor.

It seems that we get no added 'Tor security'. 

So, maybe our levels are:
* Normal (not recommended)
* Moderate
* High

Dave had some good thoughts about the explanatory text that I think will also help.

**Comment by m4mb01t4l14n0** [comment]
I'm working interactively with @cstiens on this language.  I looked at the slider on Android TBA and I think that approach is only midling-successful.  I think if we're having this idea of "levels", it's good have them labelled.  

To me, the hard thing is these levels have to communicate BOTH that there is more or less "safety" and that along with more safety comes greater interruption in the browsing experience.  That's important because an unclear-sized set of users don't understand that security/anonymity/privacy don't come for free in terms of performance.  They need to know that "just make it work" DOESN'T mean "just make it work and keep me safe at the same time".  Etc.

**Comment by cstiens** [comment]
I've done some work on this. It's here: https://docs.google.com/document/d/1FFtPEZZxERyt-eVMbaeESSi8z1WlxInrZnj3nZQqdus/edit#

**Comment by m4mb01t4l14n0** [comment]
from the UX team:  https://docs.google.com/document/d/1FFtPEZZxERyt-eVMbaeESSi8z1WlxInrZnj3nZQqdus/edit#heading=h.e60htym8y6cu

There are a few things to note:
- I've reversed the order, and labeled them 'gold, silver, bronze'. The thought is two-fold: 1) to de-prioritize the lowest level (which can be insecure) and 2) to have a system totally unique from Tor, to help lessen any confusion.
- I liked how you had given a snapshot of the browsing experience. I kept this notion, but removed the 'What's browsing like' question.
- Rather than using the word 'anonymous', I refer to things being tunneled through Tor versus not.
- I've simplified and brought consistency to the bullet points by using 'yes' or 'no' for everything.

**Comment by tladesignz** [comment]
I'm sorry, I didn't follow this discussion closely.

Here are my answers to some questions which arose here:

> What do I actually get when Universal link protection is on?

Apps in iOS can register to handle links to certain domains. Best examples: Youtube and Wikipedia. If you have these apps installed, links to them would directly open the app. These apps of course don't use the Tor tunnel. Universal Link Protections protects you from that behaviour.

Regarding the "insecurity":

Of course, if you choose the lowest level, TLS doesn't become insecure suddenly. You're just not safe anymore to always connect only via Tor. That affects certain content like audio and video, but also some JavaScript stuff like WebRTC.

While that is totally acceptable for a lot of people in the western world, and makes some sites to "just work" for these, there's 2 things to consider for people in countries with censored Internet:

1. For them, it doesn't make it "just work", because the content will often times be censored over the non-Tor connection. That's why they probably used Onion Browser in the first place.

2. People may unexpectedly knock on the censor's door with certain content on certain pages, without the possibility to tell apart which pages are safe and which are not.
After I talked to some people from problematic countries at the last conference I visited, there doesn't seem to be a huge concern among the community, that they will attract unwanted attention with that behaviour. But I still think, that's the worst case we have to consider: A user makes a request to a domain, which is censored, and access attempts are surveiled. The next morning, police picks them out of bed to arrest them for adultery/conspiracy/whatever.

And now, let's not forget: **this can also happen on level 2**!

The difference basically is: On level 1, websites don't need to do anything actively besides providing certain content. On level 2, they need to actively attack our protections, which we're unfortunately unable to completely prevent without disabling JavaScript completely. (Therefore level 3, which is really safe, but also breaks a lot of sites, which rely on JavaScript a lot.)
(See #117 for a deep discussion.)

To conclude: From the standpoint of the worst case scenario, level 1 is deeply insecure, or maybe better "unsafe", if you want to see it from that perspective.

From the best case scenario, level 1 is the "just make it work, I'm not worried with leaking my identity sometimes as long as my ISP doesn't get my browsing history most of the times" setting.

That's of course a huge difference. But I'd really preferred if we would rather lean towards the worst case scenario for communicating all of this.

**Comment by kckthx** [comment]
Here's the updated doc with a think a few comments from @cstiens permissions **_should_** be updated, but I don't have the power to change those..
https://docs.google.com/document/d/1FFtPEZZxERyt-eVMbaeESSi8z1WlxInrZnj3nZQqdus/edit?usp=sharing


I'm also uploading a screen of what the new onboarding screen would look like (shield menu would follow suit.) Now with "Gold" being the "highest" level of security it is also at the top. Also attaching a zip with the svg of the badges. 


![Define-Security-Level_31March2020](https://user-images.githubusercontent.com/36669955/78080205-5e5fee80-7373-11ea-8766-b0b6f687fdd7.png)
[New-Security_31-March-2020.zip](https://github.com/OnionBrowser/OnionBrowser/files/4411811/New-Security_31-March-2020.zip)

**Comment by tladesignz** [comment]
@kckthx, thanks a lot!

Regarding the shield, I just need the color codes. And please, also check with white on black (aka. "dark mode"), if the color codes need to be different there, an provide these, too!

**Comment by kckthx** [comment]
Awesome @tladesignz . I think the colors will be fine

![DarkMode-Levels](https://user-images.githubusercontent.com/36669955/78148548-94948100-73fa-11ea-81e0-43b90c2c0d42.png)


**Gold** FFD300 – D5A900
**Silver** CFCFCF – 6F6F6F
**Bronze** E37C00 – A05E0C

**Comment by m4mb01t4l14n0** [comment]
If it works with Dark Mode, I approve!  Great work here.
