### ISSUE TITLE
Crashes when I open app

### ISSUE THREAD

**Issue by colbywc** [OnionBrowser/iOS-OnionBrowser#264]
I am on iPad Pro third GEN using 13.1.4 the app was working fine and then all the sudden now whenever I open the app it shows the purple screen and then force closes can someone help me

**Comment by tladesignz** [comment]
Sorry to read that. To help me debug you, let me walk you through the following items:

1. I guess you mean 13.4.1? If not, please update, because old versions of iOS have security issues!

2. Did you (or your iOS behind your back) update Onion Browser to the latest 2.6.0?
2a. If yes, what version was it before? The one before? 2.5.0?
2b. If no, what version of Onion Browser is installed? (Check app store for that info!)

3. Are you a TestFlight tester? If so, please note that there cannot be 2 Onion Browser instances running at the same time. Delete the TestFlight instance in that case, release and TestFlight are the same versions, currently, anyway.

4. Did you play around with the Tor configuration? If so: sorry, can't help you. If you're unable to reach the bridges settings page before the crash, where you could remove the broken config, see 6.

5. If you're not on latest Onion Browser, try to update it!

6. Ultimate fix is to delete the app completely and reinstall fresh from the App Store. That will remove some configuration which might cause the crash. Hope, you don't loose important bookmarks. If so: I'm deeply sorry, but unable to help you further remotely.

**Comment by colbywc** [comment]
Yes I’m on 13.4.1. The version of the app I have installed is 2.6.0. And I just got a new iPad third GEN so this was the only version I’ve had I didn’t really mess with the configuration besides add blocking. I didn’t add any bridges or anything like that and I have deleted the app and reinstalled it I did have another tour browser installed but since have deleted it also. 


Sucks cuz this is my favorite onion browser

**Comment by tladesignz** [comment]
Hm. I'm running it on an iPad Air 2 just fine. I'm pretty sure it's not the hardware.

Something must be special on your configuration. Help me reproduce it!

- What language are you running?
- Do you have a VPN running? Anything else like Cloudflare DNS or similar apps messing with the network traffic?
- When *exactly* does it crash? The first time you run it after install, there's the introduction. At what scene does it crash?
- You got the app from Apple's App Store, right?
- The device is not jailbroken, I assume?

**Comment by tladesignz** [comment]
Please also hard kill all other apps running Tor. That could cause issues, too!

I'm closing that issue now, since you don't reply. Feel free to reopen, if needed.
