### ISSUE TITLE
Browser shows a direct connection after wake up from standby

### ISSUE THREAD

**Issue by sedirmohammed** [OnionBrowser/iOS-OnionBrowser#276]
If I connect to a website, i.e DDG, and open the TOR circuit tab it shows a normal tor circuit. So far, so good! But if I press the standby button of my iphone and wake up it again and now open the TOR circuit tab, the first time it shows me an empty panel, if I close the panel and open the panel again it show me a direct connection to the website?!?!?!?!? If I reload the page it shows me a new circuit to the website. Is this a display error, or does onion browser really loses the tor connection at this moment?

**Comment by tladesignz** [comment]
Thanks for your message!
Actually, that’s sort-of expected behaviour. We need to shut down Tor when the app goes in background, as iOS will silently close the network connections. Then Tor would get angry about that.

The upside is, that, once Tor has gathered a healthy amount of circuit information, restart is quick and reliable.

I agree, UI could be better around this edge case, but on the other hand, that doesn’t seem like well spent money.

**Comment by sedirmohammed** [comment]
But does that mean that there exists a direct connection to the server (i.e. DDG) after wake up and before I reload the page?

**Comment by mtigas** [comment]
@berevesero 
> But does that mean that there exists a direct connection to the server (i.e. DDG) after wake up and before I reload the page?

No.

1. The current page you are seeing was downloaded via Tor when there was still a Tor connection.
2. The onion circuit list shows the _current_ Tor connection. If it is empty (as in your example), there is no connection to the website because we have no Tor circuits open to the website.
3.  We do not fall-back to non-Tor connections. Reloading the page -- or if there is something on the page that would request new information (like how some sites dynamically refresh while you are on the page) -- then the app will create a new Tor circuit to connect to the website (after which the circuit list should show the new Tor circuit), or it will fail to load if a circuit cannot be made.

It's probably worth revisiting the text or design of the onion circuit list in the circumstance when there's no active Tor connection (i.e. after standby), but we're in a phase where we have very limited resources to work on things that aren't security bugs or [urgent impending development](https://github.com/OnionBrowser/OnionBrowser/issues/231).
