### ISSUE TITLE
Crashes when selecting text entry form field

### ISSUE THREAD

**Issue by modestmac** [OnionBrowser/iOS-OnionBrowser#279]
I’ve attempted across various sites (including .onion) using different security levels and both physical and software keyboards.  After selecting a text entry field on any site the app will crash.

Onion 2.6.1
iPadOS 14.0 (18A5332f)
MY2H2LL/A (12.9 Pro 2020)

**Comment by tladesignz** [comment]
So you're running iOS 14 Beta 3?

On my iPhone XS running iOS 13.6 it seems to work.

I browse to https://www.w3schools.com/html/html_forms.asp, tap around in the form fields, select text, delete text, enter text, all fine.

Do I need to do something more specific?

I'm actually surprised that it runs on iOS 14 at all. Would have thought, Apple has removed UIWebView support there, already.

However, there's a version 2.6.2 in the pipeline. Maybe that fixes it for you. (Newer Tor, compiled with a newer Xcode...)

**Comment by tladesignz** [comment]
Ah, I just saw 2 crashlogs for iOS 14 in AppStoreConnect with a device like yours. I guess that was you?

Unfortunately, the crashes are right at the entry point of the app. That looks very much like a problem in iOS.

Let's see, what Apple officially will say about support for UIWebKit in iOS 14 and for the release of it.

Thank you very much for your efforts!

**Comment by modestmac** [comment]
Appreciate the updates - checked a few other apps and it looks like its
only causing issues with specialty browsers - Chrome and Edge seem fine -
 but anything with TOR and the VMWare/Citrix Web Browser.

I can grab my local logs at anytime if for some reason you need them later.

Cheers and thanks again for such an awesome app

**Comment by tladesignz** [comment]
The thing is, there are 2 different web browser widgets:
[`UIWebView`](https://developer.apple.com/documentation/uikit/uiwebview) and [`WKWebView`](https://developer.apple.com/documentation/webkit/wkwebview).

[Apple has deprecated the first](https://github.com/OnionBrowser/OnionBrowser/issues/231), but we rely on it, because we currently cannot switch to a [`Network Extension`](https://developer.apple.com/documentation/networkextension) (the only way to intercept `WKWebView` traffic), because it's still too constrained for current Tor and the code that needs to surround it.

Some (slightly outdated) explanations here: https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

I would have expected them to drop `UIWebView` in iOS 14 completely, but obviously not. Seems, they give us one more year. But they really want it gone, so I can see, why the support is now buggy. Let's hope, they'll fix this before the release.

Chrome and Edge most probably already moved to `WKWebView`, therefore no problems there.

Thanks again for your efforts, they lead to interesting insights without me having to go Beta myself. :-)

I'll close this now, but feel free to reopen, in case you find more on this.
