### ISSUE TITLE
https Everywhere feature is undocumented, and UI is mysterious.

### ISSUE THREAD

**Issue by Charlweed** [OnionBrowser/iOS-OnionBrowser#285]
It is undocumented what the "rules" are, and how to use them. 
Are these portions of urls that will not be redirected to https?
Are they globs, regexes, or something else?
Is there a way to know when a redirect occured?
Are .onion paths redirected? 
Can redirection be disabled for sub-nets?
Is there a way to disable the feature entirely?

**Comment by tladesignz** [comment]
> It is undocumented what the "rules" are, and how to use them.

Actually not. At least not to the person who is willing to dig a little.

Actually, it's an implementation of this:
https://www.eff.org/https-everywhere

You can find our implementation right here on GitHub:
https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Endless/HTTPSEverywhere.m
https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Endless/HTTPSEverywhereRule.m
https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Resources/https-everywhere_rules.plist
https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Resources/https-everywhere_targets.plist

> Are these portions of urls that will not be redirected to https?

No, it's about redirecting to HTTPS in the first place for well-known sites, so you don't get man-in-the-middle-attacked while doing an initially unsecured request. This saves you the burden of typing "https://" yourself.

> Are they globs, regexes, or something else?

Regexes.

> Is there a way to know when a redirect occured?

You can also see the list of rules inside the app under Settings -> HTTPS Everywhere Rules.
This will also show you, if a rule is in use on the top tab.

> Are .onion paths redirected?

Some, yes. E.g. DuckDuckGo, as they managed to get a certificate for their `.onion` domain. However, that's not really necessary, as `.onion` sites are access directly over Tor and always encrypted. In that case, there's no exit node, which could read the clear-text on http connections.

> Can redirection be disabled for sub-nets?

No, just the rules can be disabled.

> Is there a way to disable the feature entirely?

No, because, why would you lower your security for no gain?

**Comment by Charlweed** [comment]
Respectfully, no, it is not. 
If a user does not know what "https anywhere" is, they have no hope of knowing how to use the "rules" screen. Googling that phrase is useless for figuring out the ui screen because there is no documentation on what that specific screen is for, nor how to use it. 
And even if they dig around, and end up on github, source code is not user documentation.

This issue should not be closed, so that some contributor, someday, can know that this feature is UNDOCUMENTED anywhere within the app. Then, they can create an explanation, or help, or UI, that will help some user successfully use the feature, without having a github account.

**Comment by tladesignz** [comment]
Actually, most of the features are quite underdocumented, if you see it that way.

Hopefully awaiting your contribution!
