### ISSUE TITLE
Default browser support in iOS 14

### ISSUE THREAD

**Issue by nitrohorse** [OnionBrowser/iOS-OnionBrowser#296]
Hi! This is a feature request for Onion Browser to support the ability to set it as the default browser systemwide in [iOS 14](https://www.apple.com/ios/ios-14/), similar to [DuckDuckGo](https://github.com/duckduckgo/iOS/pull/706), [SnowHaze](https://github.com/snowhaze/SnowHaze-iOS/issues/18), and [Firefox](https://blog.mozilla.org/firefox/firefox-default-for-ios/).

**Comment by tladesignz** [comment]
After some advanced search tricks, I found the document describing the process:

https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client

Unfortunately, we won't be able to apply for this:

> - Your app can’t use `UIWebView`.

We *do* use `UIWebView` because that's currently still the only viable way to get between the web rendering engine and the internet with Tor. Yes, we know that's a problem and we're working on this together with Tor Project, but it's hard.

However, there's a workaround to make Onion Browser the default pre-iOS 14. Might still work for iOS 14. Have a look at this issue, where it is described: #176

**Comment by nitrohorse** [comment]
Thanks for reply and explanation, @tladesignz; understood!

**Comment by iam-cult** [comment]
This feature would be greatly appreciated

**Comment by f03ar1** [comment]
Up.

Otherwise if someone knows how to make it work and explain (that can be understood by a mere mortal too, not only IT guys), I’d be grateful.
I read something about turning Safari off and removing other browsers, but I would actually like to keep access to other apps, maybe there’s a solution that doesn’t include that step?

Thanks.

**Comment by tladesignz** [comment]
Onion Browser 3.0.0 was released yesterday which finally could switch to `WKWebView`. I just wrote to Apple to grant the needed permission.

**Comment by tladesignz** [comment]
It's finally coming, folks!
