### ISSUE TITLE
This app crashes often especially when using swipe keys

### ISSUE THREAD

**Issue by kehnton** [OnionBrowser/iOS-OnionBrowser#303]
Hi Dev!

I’ve fallen in love with this recommended tor browser for a while. But I noticed it suddenly stops working often and it also hangs and eventually closes/crashes whenever I am entering informing using the swipe keyboard feature on my iPhone device. I currently use iOS 13.6.1 on iPhone SE.

Kindly look into it and I hope this issue gets corrected for smooth enjoyment of this great app.

Thank you!

**Comment by tladesignz** [comment]
Hi! Thanks for your note!

I can reproduce this problem when I use the app disconnected from the development environment. However, when I try to connect the debugger, it doesn't crash.

I'm sorry, but I'm afraid I can't do a lot about this. It very much looks like a problem in iOS. It seems to be in the interaction between `UIWebView` and the keyboard. I don't think I can do anything about it and since Apple deprecated `UIWebView`, I guess they won't be very interested in fixing it on their side.

I'm sorry. As long as we are unable to switch to the replacement `WKWebView` (see #47), I guess you just have to live with it. I'm going to do one last release end of the month, maybe that will help a little, but probably not.

**Comment by angakkoq** [comment]
It's the language script translator which is corrupt

**Comment by tladesignz** [comment]
> It's the language script translator which is corrupt

That sounds very interesting but I don't understand it completely. Could you get into a little more detail?
