### ISSUE TITLE
onionbrowser.com can't be reached with Onion Browser thanks to Cloudflare

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#304]
![Simulator Screen Shot - iPod Touch (7gen) @ iOS 14 2 - 2020-11-25 at 16 52 13](https://user-images.githubusercontent.com/117089/100251096-ab19ba80-2f3e-11eb-8db6-598e318017c8.png)

**Comment by tladesignz** [comment]
Folks, are we serving this from GitHub directly? We need to move this to another provider!

**Comment by m4mb01t4l14n0** [comment]
github.io

**Comment by n8fr8** [comment]
Cloudflare can be configured to not show that check for Tor. 

https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing

Otherwise, shouldn't we send users to an Onion address?

**Comment by tladesignz** [comment]
> Cloudflare can be configured to not show that check for Tor. 

Well, and do we control that for github.io?

> Otherwise, shouldn't we send users to an Onion address?

Yes, we should. Again, do we control that server to enable this?

I think, **NOT**!

We need to serve this ourselves, quickly! This does let look us really poor.

**Comment by m4mb01t4l14n0** [comment]
@n8fr8 yeah, I too do not understand how the link you provided helps us.  We're not the CloudFlare customer, github.io is, or so it seems.  Unless of course, GitHub.io surfaces a setting to let its individual customers set the Cloudflare threat level.  

Ben's right that this is a terrible situation, given we know the Cloudflare problem is unsolvable.  Maybe an alternative hosting site is warranted.  Question: does gitlab have a similar website service...that's NOT hosted by Cloudflare?

**Comment by angakkoq** [comment]
Why don't you setup a server for this yourself? One of you guys must have a
good 24/7 365 connection?

**Comment by mtigas** [comment]
i think this one might actually be my bad. (and i think relatively recent?)

a couple weeks ago i [had to shut down](https://www.webfaction.com) a server i'd been using for reverse-proxy and 301 redirects and some static file hosting, and this may have been one of the domains using it. (i believe i had it operating in front of github pages due to some paths needing redirects? something like that. this is no longer the case anymore.) the NS records actually _are_ on cloudflare at the moment, and i think when i made some of those migrations i'd errantly left their firewall/proxying bits turned on.

this should all be fixed now (i.e., you resolve straight to github pages servers, rather than cloudflare firewall servers):  
![Screen Shot 2020-11-25 at 16 18 47](https://user-images.githubusercontent.com/53129/100282594-e6fe5100-2f39-11eb-8580-0258c37e73bb.png)  
(ip address A records [per github's instructions for using the apex domain](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain))

**Comment by tladesignz** [comment]
Aaah, @mtigas, great! Thanks for fixing this so quick!

**Comment by worenga** [comment]
can you attach a .har file?
