### ISSUE TITLE
Tor-Browser leaks information from environment

### ISSUE THREAD

**Issue by emdete** [OnionBrowser/iOS-OnionBrowser#308]
my tor-browser is set to en-US but when i entered google.com it switched to german. i investigated how that could happen and found the env var LANG to be set to de_DE. after i unset LANG google did not switch to german. so google could somhow access information that should not be revealed by the tor-browser or am i wrong?

**Comment by tladesignz** [comment]
You sure you came to the right place? Because I have no idea how on earth you managed to set the LANG environment variable on iOS directly. (Without a jailbreak, that is.)

However, check your route through the Tor network. You might use a German exit node, which would explain Google showing a German translation.

**Comment by emdete** [comment]
Oups, you're right, i thought this is about the Tor-Browser made from a firefox. sorry. Which one is the right name for the desktop tor browser?

**Comment by tladesignz** [comment]
> Oups, you're right, i thought this is about the Tor-Browser made from a firefox. sorry. Which one is the right name for the desktop tor browser?

It IS Tor Browser. But this is *Onion Browser*, a Tor-enabled browser for iOS, independently made from the Tor Project. (Although befriended.)

You might start your search for support here: https://support.torproject.org
