### ISSUE TITLE
Crash after wake up

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#311]
Running iOS 14.5 devbeta in beta app can not wake-up from been in background and "crash" losing open tabs

**Comment by bruin425** [comment]
Having issues as well. In the onion browser using the duckduckgo, it won't load anything I search for

**Comment by tladesignz** [comment]
Sorry, folks, but this is way too little information.

You might have experienced that it sometimes does *not* crash when coming back? So, while it might crash sometimes (or even often) when *you* use it, that's not the case with standard usage. Otherwise we would have noticed and fixed, already.

So, there must be certain circumstances. Typically bridges? If you're using Snowflake bridges, then that wouldn't surprise me. We're working on improving that, but that's a hard nut to crack, because that's third-party code and a lot of stuff outside the realms of Onion Browser. (E.g.: there must be a snowflake available for you!)

Or it's something else which is triggered by some specific configuration and/or list of pages you have loaded.

**Comment by tladesignz** [comment]
A fix will be contained in the next release! Thank you for your patience and perseverance!
