### ISSUE TITLE
Change default guard node

### ISSUE THREAD

**Issue by Olexem** [OnionBrowser/iOS-OnionBrowser#331]
Hello,
I found that onion browser always connect guard node to Germany, even though Im in North America.

This results high latency when connecting to websites, and slower speed.

Is there a solution to connect a different/certain country's guard node?

**Comment by tladesignz** [comment]
This is all Tor machination. OB itself cannot do anything about it. You can force a guard node, when you use a specific Obfs4 bridge. (Which then becomes the guard aka. entry node.) Check bridges.torproject.org and repeat until you're satisfied.

Please note, though, that there's just a lot of nodes in Germany, because Germans seem just quite enamoured with Tor and for them it's not prohibitively expensive compared to other contries.

**Comment by Olexem** [comment]
> This is all Tor machination. OB itself cannot do anything about it. You can force a guard node, when you use a specific Obfs4 bridge. (Which then becomes the guard aka. entry node.) Check bridges.torproject.org and repeat until you're satisfied.
> 
> Please note, though, that there's just a lot of nodes in Germany, because Germans seem just quite enamoured with Tor and for them it's not prohibitively expensive compared to other contries.

Thank you for your reply.
I will try that, didn't know these things before.
:)
