### ISSUE TITLE
Bug: Removing share options does not work

### ISSUE THREAD

**Issue by eruciform** [OnionBrowser/iOS-OnionBrowser#344]
If one deactivates sharing by Safari, for example, the option still remains on the share menu. ipadOS14.7.1

Also, I'm not even entirely sure what I did, but some combination of swipe options on ipadOS14 shares either the current page or a selected tab on the tabs view to safari, and/or makes a floating safari page within the onion browser that I can't figure out how to kill. It's very confusing and not documented at all that I can find. And it's also unsafe because it just shoves whatever URL you're at now into the very not protected Safari app, including adding to it's browser history there.

I'm not sure if it's a feature request, but being able to shut off all share options, including by swipe motions, might also help in this case.

**Comment by tladesignz** [comment]
I'm afraid, that's something we can't control. That's a feature of the `UIWebView` we must use to render web pages. I know, it's annoying. I'm stumbling over this on my iPad, too, with different apps.

Turns out, you can actually turn it off. The keyword to search for is "multitasking":

https://9to5mac.com/2020/02/17/how-to-turn-off-ipad-multitasking/
