### ISSUE TITLE
Feature request: Use Firefox Android 78 as user-agent

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#351]
Currently all Cloudflare sites are blocked. But if I set
Mozilla/5.0 (Android 9; Mobile; rv:78.0) Gecko/20100101 Firefox/78.0

as the user-agent, it unblocks all Cloudflare sites.
So maybe give users choices between default iOS and Tor Android user-agent.

**Comment by Destroyinator69420** [comment]
I should try that.

**Comment by tladesignz** [comment]
Goddamnit. It really works. I would have never guessed they selectively disable captchas based on user agents.

I want this, but I'm wondering, how to integrate this in our UI.

It currently is like it is for reasons: We normally keep the iOS user agent, because if somebody fingerprints the browser, it would stand out as iOS Safari-ish with a modified user agent. If there's many of them with the identical user agent, that will flag them as Onion Browser.

@mtigas, @m4mb01t4l14n0 we need to talk about providing this. What's your take?

**Comment by tladesignz** [comment]
![Simulator Screen Shot - iPhone 5s @ iOS 12 4 - 2021-10-06 at 11 47 36](https://user-images.githubusercontent.com/117089/136180189-065d56d6-3ba0-41ff-92b0-f29e8f4a1930.png)

**Comment by tladesignz** [comment]
How about this?

This is a cheap solution. You tap on one of the buttons, and the "User Agent" field will be set to one of the 3 predefined strings. You can delete that field again (clear button will be shown on focus to assist that), and you're back to iOS Safari UA.

Please comment! Any suggestions for improvements? Wording ok?

![Simulator Screen Shot - iPhone 5s @ iOS 12 4 - 2021-10-07 at 10 39 43](https://user-images.githubusercontent.com/117089/136350024-11f00b5a-7432-4da8-adef-1aedf44dd25b.png)

**Comment by n8fr8** [comment]
Seems fine for a fast, cheap solution. In the medium term, I think we want to find a way for users who face constant cloudflare captchas to understand how to activate this alternate-UA mode to get through them.

**Comment by m4mb01t4l14n0** [comment]
Regarding both the proposed design and the comment of @n8fr8: One guesses that as soon as we formalize the set of hardwired alternative browser UA strings someone from Cloudflare will figure this out and block those strings.  Since we are in an odd situation with the App Store, I'd not want to risk our position there by submitting overly-many new builds in the name of merely updating the UA string constants.  So, perhaps we need to offer the ultimate option: allow the user to craft their own UA string in a text field (remembering they always have the option to return to the system-defined string) and, using some out of band mechanism, assist users in understanding what UA strings are CURRENTLY useful.  That text feed should support copy/paste so we can send UA strings via messaging or QRCode or other.

**Comment by m4mb01t4l14n0** [comment]
Overall, Cloudflare is a key participant in "Privacy Pass" which is their intended way for users to mitigate the problem of their self-inflicted CAPTCHA problem.    https://datatracker.ietf.org/wg/privacypass/about/

**Comment by tladesignz** [comment]
Ok, so we discussed this yesterday. Just to clarify some statements here:
- Users already *can* provide their own user agent string.
- It's obviously very hard for them without any help.
- Privacy Pass is currently not an option, because `UIWebKit`(and also mobile `WKWebKit`, AFAIK) don't support browser plugins. So, a full rewrite in Swift would be needed. See #337
- We won't update Onion Browser just for changed UA strings. They might get updated on releases we do for other reasons, though.

I'll commit the proposed solution.

**Comment by tladesignz** [comment]
Will be contained in the next release. Might take some more weeks!
