### ISSUE TITLE
Darkened web pages in Dark Mode

### ISSUE THREAD

**Issue by R8s6** [OnionBrowser/iOS-OnionBrowser#353]
OS: iOS, v14.8
App Version: 2.7.5
Device: iPhone SE (1st gen)

Hi,

I see that the Dark Mode enables dark menus, but web pages are still bright.

For example, here's today's Wikipedia front page shown in OnionBrowser iOS:
![OnionBrowser iOS Dark Mode](https://i.imgur.com/7DuRUPD.png)

And here's the same page in Firefox iOS with Night Mode:
![Firefox iOS dark mode](https://i.imgur.com/WNXXhZv.png)

As you can see, the web page in OnionBrowser is still bright, as it appears to be rendering the original page without changing any colours.

If possible, something like that in Firefox iOS, with dark background and altered font colours to match the dark background, would be greatly appreciated. 

Thank you very much!

**Comment by tladesignz** [comment]
Unfortunately, this is currently not possible, as Onion Browser is still on the old `UIWebView` instead of the newer `WKWebView` renderer. As soon as we are able to switch, this problem will go away. Sorry.
If you're interested, why this change didn't happen, yet, you can read about it a little in this issue: #47
