### ISSUE TITLE
Tor 0.4.5.10, OpenSSL 3.0, IOS 15 mitigations for video without leaking IP address

### ISSUE THREAD

**Issue by Destroyinator69420** [OnionBrowser/iOS-OnionBrowser#360]
When can we expect an upgrade to Tor 0.4.5.10 and OpenSSL 3.0? I think that Onion Browser would be better if there was a built in media player separate from safari that did not leak ip addresses. I have noticed that videos play in IOS 15 and might be leaking IP addresses.

**Comment by tladesignz** [comment]
> When can we expect an upgrade to Tor 0.4.5.10 and OpenSSL 3.0

https://github.com/OnionBrowser/OnionBrowser/releases/tag/v2.7.6
Currently in TestFlight. However, OpenSSL will be on 1.1.1l. Why do you need 3.0?

> I think that Onion Browser would be better if there was a built in media player separate from safari that did not leak ip addresses. I have noticed that videos play in IOS 15 and might be leaking IP addresses.

You're not the only one:
https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Resources/Base.lproj/security-levels.html#L257-L266

https://github.com/OnionBrowser/OnionBrowser/issues/47

I don't think it would either be possible, nor feasible, to create our own media player and have it reliably intercept and play back media data.

But worry not. Change is coming:

https://github.com/iCepa/iCepa/issues/34#issuecomment-948427515

There's(hopefully) going to be a version 3.0 of Onion Browser which finally is able to tunnel al Tor traffic. We will need some fresh UI drafts and a plan, so that will still take a while.

**Comment by tladesignz** [comment]
Latest Tor 0.4.6.9 and OpenSSL 1.1.1m will be contained in version due for release soon 2.7.8.
