### ISSUE TITLE
how to share the socksport?

### ISSUE THREAD

**Issue by xtangliang** [OnionBrowser/iOS-OnionBrowser#363]
I added --SocksPort 9999 into the advance tor config.. but it not works.
So, How can I do that?

**Comment by tladesignz** [comment]
OnionBrowser already configured a SocksPort: https://github.com/OnionBrowser/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L56

Can you just use that?

But how do you use it anyway?

Tor stops, when OnionBrowser goes into the background after a few seconds.

You could only use that from another app on iPad with an app running side-by-side, because that's the only situation, more than one app will run at once on iOS. (With certain exceptions.)

Or do you want to use it from another device on the same WiFi?

In theory, iOS lets you open ports on the network interfaces for listening, and one would assume that Tor will bind on all interfaces, when you omit the IP address, but in practice, that could not be the case.

Try explicitly mentioning the interface you want to use. (Wifi, that is. I really don't recommend using the mobile network interface!)

Try using other ports. E.g. I know I can run a web server on port 80 on iOS.

Hope that helps!

**Comment by tladesignz** [comment]
Correction: I'm actually not sure, if iOS actually allows you to open a server on port 80. Confused some things there.

**Comment by n8fr8** [comment]
well, probably 8080 though right? Non root user mode?
