### ISSUE TITLE
App crashes when using Scribble

### ISSUE THREAD

**Issue by bbqthis** [OnionBrowser/iOS-OnionBrowser#366]
When I try to input text into a field (ex. DDG search field) using Scribble with Apple Pencil, app crashes instantly.

**Comment by tladesignz** [comment]
Thanks for mentioning this. The complaints about crashes when doing something with form fields started since iOS 14. I'm afraid, this is due to Apple not wanting to support `UIWebView` any longer but too many apps still relying on it, so dragging it forward in an ugly way.

We're quite near a solution to replace `UIWebView` with `WKWebView`, but that still some months away. Please be patient until then. Thank you!
