### ISSUE TITLE
Bad alignment on IPhone 13

### ISSUE THREAD

**Issue by Fl1tzi** [OnionBrowser/iOS-OnionBrowser#367]
On my IPhone 13 it seems like the overall UI doesn't fit with the new notch.
![image](https://user-images.githubusercontent.com/76444201/147617181-8e094aff-5acb-4833-9159-1c5f9e598a9d.png)

**Comment by tladesignz** [comment]
You mean, because of the "Suchen" system button which overlays our UI slightly? I actually doubt, that this was better on iPhone X/XS/12. Besides that, I can't see any specific issue with the slightly smaller iPhone 13 notch. (Tested on my personal new iPhone 13.)

Since that button only shows, when one app is called from another, and everything is still usable, including the shield and that back-to-other-app button, I'm not inclined to sacrifice more screen estate to accommodate this stupid button, which always was a really ugly UI hack Apple never should have done in the first place. Esp. not, when you're entering from an app search.

Sorry. I'll close this. Feel free to re-open, should I have missed something here.
