### ISSUE TITLE
Can't build in Xcode 13.2.1

### ISSUE THREAD

**Issue by plutonianmusic** [OnionBrowser/iOS-OnionBrowser#370]
I'm new to Xcode, so forgive me if I'm missing something obvious.

I've followed the build instructions, but can't seem to build the project.  The error is from IPtProxyUI - "No such module 'IPtProxy'" - on the line "import IPtProxy" in MeekURLProtocol.swift.

I've started 3 times from a clean git clone.  BartyCrouch is installed.  I've edited the podfile multiple times, thinking that the versions might need updating.  I always start Xcode from OnionBrowser2.xcworkspace, not .xcodeproj.  I've downgraded the target versions for each pod, and tried different simulator versons.  Can you point me in the right direction?

**Comment by tladesignz** [comment]
Sounds strange. I don't really have a good idea, because "it works for me" and there's no clue in your description what might be off.

Try `pod update` 2 times in a row to ensure, the `IPtProxy` dependency installs its binary piece correctly. (And check that project's readme to understand what's going on there!) Also fix `Tor.framework` to 406.8.2, because the latest version still has problems with Onion Browser.

**Comment by plutonianmusic** [comment]
Thanks for the suggestions - I really appreciate the fast response.  I ran pod deintegrate, then pod update (twice).  Opened the new workspace and ran the build - same error.  In the IPtProxy readme, they recommended specifying v1.4, so I edited the podfile, deintegrated, updated (twice), opened the workspace and ran the build.  Same error, but this time also a warning:  "Could not read serialized diagnostics file: error("Invalid diagnostics signature")" from module MoatViewController.dia.

The build instructions for IPtProxy also suggest "This will create an `IPtProxy.xcframework`, which you can directly drop in your app, if you don't want to rely on CocoaPods." OK, I am using CocoaPods, but a folder named "IPtProxy.xcframework" was created; if I want to try the workaround how should I add the IPtProxy framework to the OnionBrowser project?

Is it possible that these issues are specific to Xcode 13?  Or could it be that I'm picking a target with too high a version of iOS?  I didn't see any recommendations on targets, but I thought I'd ask.

By the way, I'm just coming off a successful Android project that incorporated the OnionProxyManager code.  Many mods were required to make OPM compatible with the latest version of the OS, but it works like a charm.

**Comment by tladesignz** [comment]
Sorry, something with your setup seems completely off.

You shouldn't kill the workspace. That's good as it is. Then you also don't need to meddle with the target settings, they're good as they are.

Deviating from the instructions in the `BUILD.md` file, just do this:

- Do a fresh `git clone` 
- Edit the `Podfile` to fix Tor.framework to 406.8.2
- run `pod update`. (Twice to be extra sure.)

That's all.

For any other issues you run into, I'd rather search in your system setup. E.g. running in a virtual box might be a problem.

Since this is not a tech support helpline, we need to close this now, sorry. Good luck!

**Comment by plutonianmusic** [comment]
I tried the simplified instructions (above) without success.  So I started over, yet again.  This time, I see the podfile specifies use_frameworks! - and Tor.framework is not listed explicitly (version 406.9.2 gets installed; I'm not sure how to downgrade it to 406.8.2).

This is a new physical Mac Mini, not a virtual box, running Big Sur (11.6.1) and a new installation of Xcode 13.2.1.  I'm following the instructions in the current BUILD.md file, including overriding OB_APP_BUNDLE_ID[config=Debug] in Config.xconfig, but the project build produces fatal errors. 

Are there development tools, apart from Xcode itself (and homebrew for bartycrouch), that everyone installs and that I need to build this project?  There must be some implicit assumptions in the build procedure about the typical development environment.

**Comment by tladesignz** [comment]
Yes, I updated everything yesterday. It now compiles on latest MacOS Monterey with the latest Tor, Snowflake and Obfs4proxy.

That should actually be quite obvious, looking at the latest commits I did. I invite you to have a look at these before asking questions.

The latest Tor.framework now gets compiled on your machine during build, instead of using pre-compiled binaries. You will need to have a look at these build instructions, too.

Thanks for the hint, I will add that to Onion Browser's build instructions.

Besides that, my support ends here. Good luck!
