### ISSUE TITLE
"Connect to Devices on Your Local Network?" loading screen/prompt

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#372]
![this screen](https://user-images.githubusercontent.com/34868071/155763473-8537f776-522a-4e4e-86e6-141c731bd4fa.png) pops up when starting Onion Browser. iOS 14.8.1;  version  2.7.7

**Comment by tladesignz** [comment]
Hm. Can't reproduce.
I only have hardware devices on iOS 15 now.
Simulator iOS 14 doesn't show this.

It's probably because of this:

https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads

We need this, because it's a browser and we should allow people to browse on non-HTTP sites.

There's more fine-grained options available in newer OS versions, which we only target anyway, but I don't want to change something, as long as I can't debug it properly.

Is there anything else I need to do? Was there a special page trying to load on start?
