### ISSUE TITLE
Can't access some websites

### ISSUE THREAD

**Issue by github2099** [OnionBrowser/iOS-OnionBrowser#374]
When I click on some links to direct to another page (same domain), it shows the home/start screen of OnionBrowser (the purple one), and the url is blank. Not too sure why. I even downgraded to use Bronze. It isn't an issue on desktop Tor Browser :(

**Comment by tladesignz** [comment]
Can you provide some examples?

**Comment by github2099** [comment]
YouTube, Dailymotion, etc...

I have to press and hold then press "open" to select a video. 
But even I do that, the media won't play.
I notice that many times, the progress bar (under address bar) will go 90% and stop there, never complete.

I tried uninstall, reinstall, but not fixed


edit:  I use Onion Browser with Lockdown.

**Comment by tladesignz** [comment]
Videos are difficult. We can't route them through Tor in Onion Browser, due to technical limitations of the platform.

You can inform yourself here about the details of what the security levels mean, which should help you deal with that problem:

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Resources/en.lproj/security-levels.html
(In Onion Browser this page is shown when you tap the shield icon left of the address field, then press "Learn more")

If you're in a censored area, you won't be able to access videos, though. Because, as said, Onion Browser cannot route videos over Tor.

> edit: I use Onion Browser with Lockdown.

Not sure what you mean with "Lockdown"?


Anyhow, we now have a fresh solution for you, when you want to watch video over Tor:
[Orbot iOS](https://apps.apple.com/us/app/orbot/id1609461599)
This will route *all* device traffic through Tor.

Onion Browser will soon receive an update to work with Orbot, but in the meantime, don't use it together with Onion Browser - that would create Tor over Tor which probably doesn't work, and if, only really badly.

**Comment by github2099** [comment]
>    Not sure what you mean with "Lockdown"?

Lockdown is the app on iOS that blocks ads and trackers
