### ISSUE TITLE
Cannot search in page / request desktop site on iOS

### ISSUE THREAD

**Issue by burnce** [OnionBrowser/iOS-OnionBrowser#375]
The onion menu while essential seems to mask other useful functionality.

If they are present somewhere, the usability could be improved, if not, the following features should be surfaced somewhere:
- Search in page
- Request desktop site

**Comment by tladesignz** [comment]
> The onion menu while essential seems to mask other useful functionality.

There's no masking anything, no.

> * Search in page

Good idea, we currently don't have that.

> * Request desktop site

This is technically achieved by changing the so called "User-Agent" string, which gets transmitted with every request.

Since you can provoke different behaviours from different servers, esp. when behind Tor, and it also has privacy considerations, this is a quite hard nut to crack UI-wise, which we didn't came round to, yet.

However, there's rudimentary support.

To change it for all sites:
-> Settings -> Default Security -> Scroll to bottom -> Set your own, custom user-agent string or choose one of the 3 provided below.

To change it for a specific site:
Browse to that site -> Settings -> Custom Site Security -> Add Site -> check if prefilled URL is good -> + -> Scroll down -> same as above

or shorter:

Tap shield button to left of URL box -> Customize -> Scroll down -> same as above

**Comment by tladesignz** [comment]
Related issue: #358

**Comment by tladesignz** [comment]
"Find in Page" feature added with 576f9fb9c70b0e5751a1f41ca755079520dbb4fe and released with version 3.0.0. Only works from iOS 16 onwards, since that provides a neat UI for it, which could I could implement cheaply.
