### ISSUE TITLE
Long loading time when switching between iPhone X 15.3.1 apps

### ISSUE THREAD

**Issue by iAecoo** [OnionBrowser/iOS-OnionBrowser#379]
https://user-images.githubusercontent.com/102431787/160252241-6e0916f8-0a5d-4a30-8d61-00201b4fdf27.MOV

When switching between applications, the browser takes a very long time to load. This is not observed in other applications. One browser may have just been opened and not have any tabs open, but the download is still long

**Comment by tladesignz** [comment]
Yeah, sorry, this is well known. When the app is backgrounded, it's really halted. I.e. it doesn't get any more processor time. We need to stop Tor before that happens and later restart it when the app comes into foreground again. If you're in a censored environment, that may make it extra-slow.

There's a Onion Browser 3 on the horizon, which will work completely differently under the hood and which will resolve many of these little problems. Will still take a while, though.

In the meantime, another option is, to use the recently released Orbot iOS with the browser of your choice: https://orbot.app

If your goal is to stay anonymised, though, not just escape censorship, be warned that it will not really work with Onion Browser and you will need to find another browser which provides all the help on the higher application (HTTP) level to stay anonymous.

**Comment by iAecoo** [comment]
I want to suggest adding the removal of browser windows by swipe to the
left, similar to Safari.

It often happens that it is not possible to get into the small cross and
the window that I planned to close opens. If there are a lot of windows, it
turns out to be very inconvenient.

Also, sometimes open windows disappear from the list and appear only if you
open a new window and then you can select the desired one. It happens
rarely and I do not know how to record this moment.

Thank you for your answers

**Comment by tladesignz** [comment]
> I want to suggest adding the removal of browser windows by swipe to the left, similar to Safari.

There is a swipe to the top implemented. You may want to use that in the meantime. I'll think about your suggestion to change it to whatever exactly Safari does. Thank you!

> It often happens that it is not possible to get into the small cross and the window that I planned to close opens. If there are a lot of windows, it turns out to be very inconvenient. 

Yeah, I know. I'm also unhappy with that scene, but when I implemented this, it turned out, it's really a lot and hard work, to have all this working smoothly. E.g. in iOS there cannot be defined "landing zones" around buttons. So a better accessible button would eat a lot of space.

Unfortunately, our funding isn't big for "frills" like this. Sorry.

> Also, sometimes open windows disappear from the list and appear only if you open a new window and then you can select the desired one. It happens rarely and I do not know how to record this moment. 

Yeah, I experienced this one too, and it befuddles me. No idea why this does happen.
Recently I implemented a change, though, triggered by initial work from a contributor, where we switched from using the real web views and instead use snapshot images. That might fix this problem, too: #388

That will be contained in the next version due for release, soon!

> Thank you for your answers

You're welcome! Thank you for your feedback!
