### ISSUE TITLE
CA Cert in iOS 12 ipad and Onion Browser

### ISSUE THREAD

**Issue by dme1sc** [OnionBrowser/iOS-OnionBrowser#380]
Hi, I have an iPad that has a CA cert installed.  I can access the .onion address just fine with the Onion browser app but the CA cert is to allow a certified connection to a .local address,  When I try to go to the .local address, it fails with an error:  bad url 1000 domain NSURL Error Domain.  I can reach this .local address using a firefox browser on a PC with the CA cert installed in it.  Do I have to install the CA cert in Onion Browser also?  I was told Onion browser could access .local sites.
Thanks
D

**Comment by tladesignz** [comment]
Hi! No, Onion Browser cannot access `.local` addresses. When you connect through Tor, you connect through a chain (also called a "circuit") of 3 servers (also called "nodes") to the outside world. The last node is the "exit node". That's the one who does the actual connection to the target server for you. Since that server is out on the open internet, it **cannot** reach back into your own private LAN, where the `local` top level domain is meant to be in.
