### ISSUE TITLE
Review features for v3

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#381]

**Comment by tladesignz** [comment]
List of features potentially impacted by a change to Orbot as Tor provider:

- Onboarding:
  -  "Connect to Tor" button
  - Slideshow while Tor starts
- Security:
  - Content Policy: This is done by mangling the HTTP Content-Security-Policy-Header of a webpage before pushing it into the web view, probably not possible anymore
  - WebRTC: Suppressing this never fully worked. Should be removed.
  - Mixed-mode Resources: Done by intercepting traffic to web view. Probably not possible anymore.
  - Follow Onion-Location Header Automatically: Unclear, if this still can be done. With JavaScript?
- Cookie handling might need change a lot (not so much with what we do, but how we do it)
- Domain blocking will only work with a "Content Blocker Extension". Move to Orbot?
- HTTPSEverywhere might only work for user-entered URLs. Can work in content blocker extension
- TLS Version enforcement probably not possible any more
- Advanced Tor configuration not possible anymore. Add to Orbot? More finer grained config options instead?
- Tor circuit display for current website needs to be acquired via Orbot
- Request new circuits to be built needs to be signaled to Orbot and/or implemented there
- Bridge support, bridge configuration moves to Orbot (Orbot app already supports getting opened with that scene)

Anything else?


https://developer.apple.com/documentation/safariservices/creating_a_content_blocker

**Comment by tladesignz** [comment]
@cstiens, @n8fr8 let's set up a meeting to talk about this!

**Comment by n8fr8** [comment]
List of features potentially impacted by a change to Orbot as Tor provider:

- Onboarding:
  -  "Connect to Tor" button
  -- if external, need some kind of "activate Orbot" 
-- onboarding will completely change since Tor setup/start is in Orbot
-- allow app to start Orbot via custom URI; test if URI scheme is handled or not
-- HTTP local server API: report status, perphaps local SOCKS and HTTP ports
-- allow 3rd party apps to query circuit info to allow display in app? concerns about de-anon, malicious apps?
  - Slideshow while Tor starts
  -- understood
- Security:
  - Content Policy: This is done by mangling the HTTP Content-Security-Policy-Header of a webpage before pushing it into the web view, probably not possible anymore
  ---- ok; again, check for flag/api in WkWebView
  - WebRTC: Suppressing this never fully worked. Should be removed.
  ---- yes, and also this is handled by the network extension now?
  - Mixed-mode Resources: Done by intercepting traffic to web view. Probably not possible anymore.
    ---- not possible since we aren't intercepting at the page level in the browser component
    ---- is there a flag in WkWebView?

  - Follow Onion-Location Header Automatically: Unclear, if this still can be done. With JavaScript?
  ---- Content Blocker extension embedded in Onion Browser
- Cookie handling might need change a lot (not so much with what we do, but how we do it)
----

- Domain blocking will only work with a "Content Blocker Extension". Move to Orbot?
---- move to orbot, or don't support for now

- HTTPSEverywhere might only work for user-entered URLs. Can work in content blocker extension
---- Content Blocker extension embedded in Onion Browser

- TLS Version enforcement probably not possible any more
- Advanced Tor configuration not possible anymore. Add to Orbot? More finer grained config options instead?
- Tor circuit display for current website needs to be acquired via Orbot
--- via authenticated local http API

- Request new circuits to be built needs to be signaled to Orbot and/or implemented there
--- via authenticated local http API

- Bridge support, bridge configuration moves to Orbot (Orbot app already supports getting opened with that scene)
--- yes

Anything else?


https://developer.apple.com/documentation/safariservices/creating_a_content_blocker

**Comment by ghost** [comment]
Thanks for Informing us

**Comment by cstiens** [comment]
Here's a quick preview of the onboarding flow of Onion Browser that now relies on Orbot:

https://user-images.githubusercontent.com/1434597/232846855-b10a4c65-0ad0-4d1b-ac78-ef28318c8a02.mov

Here's a longer video with more explanation. It was too big to upload as a video file.
[OB+Orbot.zip](https://github.com/OnionBrowser/OnionBrowser/files/11264231/OB%2BOrbot.zip)

Additional cases are accounted for in the Figma file.
