### ISSUE TITLE
Error Code -1005

### ISSUE THREAD

**Issue by givememulch** [OnionBrowser/iOS-OnionBrowser#384]
I was trying to go onto an onion link after ages and got this error, like after a second of pressing search it just pops up with the error. And I’m currently on IOS.

**Comment by tladesignz** [comment]
This code means "The network connection was lost."

A quick search on the net gives the impression, that this error happens a lot in conjunction with misconfigured firewalls and VPNs. Might be on your side or on the exit node's side.

*Also*, this is what you will get, when you try to connect to an onion service which is secured with an auth cookie (aka. a key).
This is why you will see the error dialog offering a key entry field.

You need to provide that, in order to connect.


Unfortunately, if you don't provide any more details (like the URL), we can't help you any better. Good luck!
