### ISSUE TITLE
iOS App too high

### ISSUE THREAD

**Issue by aleff-github** [OnionBrowser/iOS-OnionBrowser#391]
In the Onion Browser for iPhone screen, the above part undergoes the iOS "Back to Back" feature.
You should lower the maximum height by a few px otherwise some buttons become untouchable.

I have an iPhone 13.

![](https://i.ibb.co/FzhXCL9/photo-2022-05-19-15-48-59.jpg)

**Comment by tladesignz** [comment]
Yeah, I know that this happens.

The only proper solution I currently see, though, is moving everything a little lower. That would mean ~10 (logical) pixels of whiteness just for this. I'm actually not prepared to give up even more screen estate for the top toolbar.

Especially, since I am still able to touch all buttons just fine. I guess others with bigger fingers might get problems there, but on the other hand - how often do you need the shield and the lock button, anyway?

**Comment by aleff-github** [comment]
oh no problem it isn't a lot relevant, I just sent you this issue but I didn't know that it is known, otherwise I wouldn't posted it. (:

**Comment by tladesignz** [comment]
Don't worry. Thank you very much for getting in contact, anyway!
