### ISSUE TITLE
Cannot login to site on iPhone

### ISSUE THREAD

**Issue by larry159** [OnionBrowser/iOS-OnionBrowser#394]
Onion browser on iPhone I go to login page no problem after entering credentials click login browser refreshes and switches IP addresses does so each time screen refreshes. Error connection error cannot reach site.

**Comment by larry159** [comment]
original connection to IP 185.220.101.38 after login server shows connection to 185.220.101.9 browser shows original IP, Same results on two different servers, several attempts version 2.8.0, same result using bridge or not.

**Comment by larry159** [comment]
When using the Onion Browser, Apache server logs show the browser logging on, collecting all of it's resources, images, CSS, JavaScript, etc., like:

berlin01.tor-exit.artikel10.org - - [06/Jul/2022:12:07:54 -0400] "GET /roundcube/program/resources/blank.webp HTTP/1.1" 200 7759 "https://mail.XXX.net/roundcube/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/605.1.15"

There's a lot that it fetches and a lot of log messages.  All from berlin01.tar-exit.artikel10.org (varies between usage, but consistent within the session).

Then you get the "failure to reach server" messages.  Apache logs shows this:

tor-exit-64.cccs.de - - [06/Jul/2022:12:08:17 -0400] "POST /roundcube/?_task=mail&_action=refresh HTTP/1.1" 200 8169 "https://mail.XXX.net/roundcube/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"


The above message is repeated forever.  What's really weird is that it is posting an action to refresh the mailbox, but it is coming from a different source.
And it is always the same source, tor-exit-64.cccs.de

Doesn't happen when you use Tor directly; works as expected.

**Comment by larry159** [comment]
Solved problem by setting Custom Site Security to Content Policy, Open, Universal Link Protection , Off and User Agent to Tor Browser Mobile Android.

**Comment by tladesignz** [comment]
Universal Link Protection is a feature to keep you from jumping into an installed app, which has registered a certain domain you just tapped. Instead, you're kept inside Onion Browser. So this should make no difference.

Tor typically tries to keep using the same circuit for the same destination server, in order to not mess up sessions bound to an exit node IP address. So jumping circuits/exit nodes should actually not happen.

Maybe the connection to your server switches between IPv6 and IPv4? 🤔 Do you have some hardcoded IPs in the links?

We have problems with Cloudflare. Using a standard user agent makes a difference there. Is your service behind a Cloudflare proxy?
