### ISSUE TITLE
Question: How to apply lessons learned from OnionBrowser to IPFS?

### ISSUE THREAD

**Issue by Gene-Dana** [OnionBrowser/iOS-OnionBrowser#395]
HI there ! I was lead here from this inspiring discussion 

https://discuss.ipfs.io/t/is-it-possible-to-create-an-ios-android-application-that-serves-as-an-ipfs-node/11957

> People said the same thing about running full Tor on a mobile device ten years ago, and yet here we are today with Orbot, Tor Browser for Android, Onion Browser, Briar, OnionShare and more.

> To truly achieve the decentralized web, we need all devices to be full, participating clients.

We are seeking to run an IPFS node from our Flutter application, and I'd like to learn more about the development challenges that the OnionBrowser faced and how the team overcame them.

At the end of it all, any wisdom you can share in this endeavor would be helpful ! 🙏🏼

**Comment by tladesignz** [comment]
Ok. Here is a brain dump from what I learned from Onion Browser, [Orbot iOS](https://github.com/guardianproject/orbot-ios), [OnionShare iOS](https://github.com/onionshare/onionshare-ios/) and [Save](https://github.com/OpenArchive/Save-app-ios/):

1. Here is some background knowledge about iOS processes, memory management and "Network Extensions":
https://benjaminerhart.com/2018/03/state-of-the-onion-ios/
https://benjaminerhart.com/2022/02/orbot-ios-released/

2. Most carriers use CGNAT (carrier-grade network address translation) for IPv4, nowadays. (Not sure about IPv6). Most WiFI routers do use NAT, too, of course. So you'll always need to be able to go through a NAT. Not an issue with Tor; I don't know what IPFS offers in terms of NAT piercing.

3. In order to distribute a Network Extension, you'll need to have an organization with a [DUNS](https://en.wikipedia.org/wiki/Data_Universal_Numbering_System) and [enroll](https://developer.apple.com/programs/enroll/) as such. Apple doesn't allow Network Extensions by individual developers.

4. I *highly* doubt, that Apple is fond of the idea of having a Network Extension, which acts as a server to the public Internet. (Or a subset thereof.) The intention of the Network Extensions API is clearly to allow cross-platform *client* implementations (they work on MacOS, too!) of VPNs and other special networks. *Not* to allow serving up files to the world in the background.
We have yet to create a burner project, which tests this, though. (Happy, if you'd do that. Please report the outcome!)

5. If you therefore *can't* rely on a Network Extension, you're stuck to 1 process which' lifecycle is fully controlled by the OS. The typical maximum you can achieve is 3 minutes of background time, after the user left the app.
Check out the [OnionShare source code](https://github.com/onionshare/onionshare-ios/) on how this is done.
(See [API docs](https://developer.apple.com/documentation/uikit/uiapplication?language=objc), section "Managing Background Tasks".)

6. An app is typically not killed, when the user moves it in the background, but suspended. (Meaning, it just doesn't get any more processor time.) *Additionally*, all open networking ports are closed. So, you'll need to make sure, that your networking code either can handle the situation, that ports go away seemingly randomly and self-heal that situation, or that you stop and restart that code at the appropriate times. (The system provides app lifecycle callbacks.)

7. There is another API, which allows you to up- and download stuff in the background, when the OS finds it convenient for you to do so. The use-case is, you're an app that shows often updated data from a server and it's convenient for the user, that this data is up-to-date, immediately after the user opens the app. I played with this API back and forth. I tried and tested it really hard for an app called [Save](https://github.com/OpenArchive/Save-app-ios/). I gave up on it. The only thing you can do with this is hand over a URL, some headers and a file system location and let the OS do the up- or downloading. Absolutely no wiggle room to do anything else, like negotiating something with a server before that. If you try, you're either crashed or blocked indefinitely, depending on the exact circumstances.

8. There is a new Extension API, which is meant for decrypting push notifications and can do some work in the background. I didn't look into that closely, yet. Maybe, there's some leeway there, but you will need a push notification server to make use of it and I doubt, you'll get a lot of processing time, either. iOS has lots of measurement mechanisms built in, which are used to punish your app for bad behaviour.

9. Be careful with any Extensions you might want to use. They're basically an app-packaged-in-an-app and have their own set of access privileges. You will need to make use of "App Groups" (a shared storage location outside the app containers) to share access to files and you will need to think about concurrency. (Every app and extension is its own process. Might get ugly with SQLite database access and similar.)

10. If you want to develop a mode, which allows the user to run a file server in the foreground, you're best bet is to create a scene which is dedicated to that, in which you tell the OS to not switch off the lights. Then add a dimmer yourself after a timeout and make use of the proximity sensor, which switches off the screen when the user is phoning. That way, users can start that and lay the phone on the table upside down and not burn too much energy while serving up stuff and don't have an involuntary nightlight. Check out OnionShare, it does exactly that. Like many of the upload-photos-in-background-to-[my cloud storage|my NAS|whatever] tools, too.

Good luck and keep us posted about your progress!

**Comment by Gene-Dana** [comment]
Wow this is awesome thank you so much ! You've greatly accelerated our progress ! When I have an update I can share it with you here ! Thank thank thank you !

**Comment by tladesignz** [comment]
> Wow this is awesome thank you so much ! You've greatly accelerated our progress ! 

You're welcome!

> When I have an update I can share it with you here ! Thank thank thank you !

Looking forward to  that!

Have a good time!
