### ISSUE TITLE
Screen restore from screenshot blocking "blur" too slow

### ISSUE THREAD

**Issue by ericswpark** [OnionBrowser/iOS-OnionBrowser#402]
Whenever I leave Onion Browser or pull down the notification shade/control center, the screenshot blocking "blur" thing kicks in and obscures the browser. The trouble is when I return to the app the "restore" time is way too slow to be usable. This becomes increasingly annoying when you're referencing another app for some data to type in, or if you're pulling down the control center to change a setting repeatedly. 

It would be great if this delay can be minimized. Alternatively I hope the screenshot disabling thing can be disabled. I'll file a separate feature request for that.

**Comment by tladesignz** [comment]
@ericswpark, thank you for your suggestions. However, it's not the screenshot disabling which is the problem.

Onion Browser needs to stop Tor before it goes in the background and restart it, when it returns. This is what delays the restart.

While I would have some ideas on how to improve that, I honestly don't want to change this anymore, since we're currently working on version 3, which will rely on Orbot and won't have this problem anymore.

Be patient!

**Comment by ericswpark** [comment]
@tladesignz thank you for the explanation! I'll wait for the revamp of course.
