### ISSUE TITLE
Reload favicons of bookmarks every time a bookmark gets selected

### ISSUE THREAD

**Issue by abdallahalsalmi** [OnionBrowser/iOS-OnionBrowser#406]
Hi, we noticed the BBC logo (and other logos) on the landing page of Onion Browser (iphone SE, iOS: 16.2) do not appear.

The problem seems to vary from one device to another on the same model. 

Sometimes the logo of Deutsche Welle doesn't appear either.

**Comment by tladesignz** [comment]
Yeah, I know, but thanks for pushing this.

The reason is: The icons are loaded on first start. On difficult connections, esp. the first requests done might time out. It's never retried until you edit the bookmark.

I guess, there should be a mechanism that retries loading the favicons at random times.

**Comment by tladesignz** [comment]
Since favicons also change, maybe the easiest solution is to reload it every time a bookmark is selected?

**Comment by tladesignz** [comment]
Ok, so icons will now be cached for 24 hours, then re-requested, if user navigates to the bookmarked website.

Might take a few weeks until released!
