### ISSUE TITLE
Updating BBC logo on landing page as per new branding/visual identity

### ISSUE THREAD

**Issue by abdallahalsalmi** [OnionBrowser/iOS-OnionBrowser#407]
Hi, 

The BBC logo have changed since mid-2022. Could you please update the one on the browser's landing page? 

The logos/visual identities can be found here: https://www.bbc.co.uk/branding/

**Comment by tladesignz** [comment]
The icons shown is your server's favicon at the time of first start of Onion Browser.

I have to think about if it's a good idea to update bookmark favicons regularly. Since the webview and our bookmark favicon handling is completely separate thanks to iOS architecture, I'm not sure, if it's a good idea to reload it every time the user hits your site.

I'll handle this in your other issue #406.
