### ISSUE TITLE
V3.0 For Existing Users With Orbot

### ISSUE THREAD

**Issue by cstiens** [OnionBrowser/iOS-OnionBrowser#423]
![00OB-withOrbot](https://github.com/OnionBrowser/OnionBrowser/assets/1434597/9defb861-e9de-4a40-9cc9-17f615800505)

@tladesignz I would do this for existing users that have Orbot installed. Keep it short and sweet. They don't need to walk through the full step-by-step process. So keeping it simple and direct is best I think.

Here, I would keep them in the browser view and disable all of the actions. I know we've had various opinions and discussions about disabling. But, let me know if it's possible and sound from your perspective. The goal is to keep them in the browsing environment.

For all other cases, meaning when users upgrade and they don't have Orbot installed, we will keep the design you have implemented that walks them through the onboarding process for Onion Browser Version 3.

**Comment by tladesignz** [comment]
> @tladesignz I would do this for existing users that have Orbot installed. Keep it short and sweet. They don't need to walk through the full step-by-step process. So keeping it simple and direct is best I think.

Well, yeah and no.
- I can drop the first scene ("welcome") for 2.x users.
- I will change the title language as suggested above for users who already have Orbot installed, in the "request permission" scene.

But it cannot get simpler than that. This is part of 1-time onboarding. There's still the "Tor must run" scene later.

> Here, I would keep them in the browser view and disable all of the actions. I know we've had various opinions and discussions about disabling. But, let me know if it's possible and sound from your perspective. The goal is to keep them in the browsing environment.

No, that would be a huge rework and I don't think it makes sense. In that state, you cannot (and *should not*) do anything useful there. We cannot even show old web pages, as we're freshly installed.

Also, remember: 2.x users are used to a startup loading scene every time they start the app. So this is already progress.

This is different to what I mentioned a few days ago: That we might think about keeping users in the browsing environment, even when Orbot is disconnected, so they can still look at their opened webpages. (Which still needs research, since we need to make sure, that users cannot trigger any requests.)
