### ISSUE TITLE
Memory Issues with Orbot

### ISSUE THREAD

**Issue by givememulch** [OnionBrowser/iOS-OnionBrowser#446]
Hey there, I’ve been completely unable to use Orbot for weeks now because of some memory issues. The circuit will connect and reach 100% and be connected fora few second s and then disconnect. If I try start it again, it just loads 0% and then disconnects. Here is the log I keep getting:  
We're low on memory (cell queues total alloc: 528 buffer total alloc: 5259264, tor compress total alloc: 0 (zlib: 0, zstd: 0, lzma: 0), rendezvous cache total alloc: 0). Killing circuits withover-long queues. (This behavior is controlled by MaxMemInQueues.)

All the error logs are about memory and I’m not sure what to do.
Thank you.

**Comment by tladesignz** [comment]
Yeah, we know. Sorry. We're tied here. I gave background info in these issues, where you can read about it:

https://github.com/OnionBrowser/OnionBrowser/issues/443#issuecomment-1764187964
https://github.com/guardianproject/orbot-apple/issues/79#issuecomment-1748365503
https://github.com/guardianproject/orbot-apple/issues/81#issuecomment-1776909258

To remedy this situation, switch to iOS 17, if you haven't, yet. Then you can use the Tor, which we built into Onion Browser, again, since it is now supported by `WKWebView`, and which isn't memory constrained.

Keep in mind, though: The old problems of Onion Browser 2 are back:
- WebRTC will leak your real IP address to all pages you visit and care to find out.
- Audio/video isn't tunnelled through the the built-in Tor, since that is handled via a completely different OS component which cannot be intercepted.
