### ISSUE TITLE
Link previews a potential security issue?

### ISSUE THREAD

**Issue by flexyboooy** [OnionBrowser/iOS-OnionBrowser#449]
The other day I noticed that when I press and hold a link on a website to open in a background tab and I hold a little longer a preview of the target URL is loaded and displayed.

I was wondering if this might be a potential security issue because it is not immediately obvious if this is an OS feature and the URLs data might not be retrieved via the Tor network but via the regular network connection (outside of Tor), although it does show the Onion network URL on top so I am assuming there is no data being leaked.

Example below.

<img width="290" alt="preview" src="https://github.com/OnionBrowser/OnionBrowser/assets/102152250/1605947b-6e56-48ea-b68c-e7e9f7f343e7">

**Comment by tladesignz** [comment]
Ha! Good that you reminded me of that.

Since you cannot reach `.onion`-addresses without a running Tor, you can rest assured, that you didn't leak anything. (Despite what you might leak always.)

However, I have to admit, that, when I added in-app Tor support again, I totally forgot about this one.

Turns out, though, that this preview-`WKWebView` seems to automatically inherit the `WKWebViewConfiguration` of its parent. (And therefore requests get proxied through Tor, too.)

I nevertheless changed the instantiation to an explicit version, just to be extra sure, in case there will be changes to the underlying Apple code in the future.


Thanks for the hint!

**Comment by tladesignz** [comment]
d1700279df65ab0aa16f616ddf1c9c4ef070e8b6
