### ISSUE TITLE
Download File Error

### ISSUE THREAD

**Issue by givememulch** [OnionBrowser/iOS-OnionBrowser#459]
Hi there, 
![IMG_6071](https://github.com/OnionBrowser/OnionBrowser/assets/78700192/0b7d3f5e-24ae-4b3c-92e3-e65a5cb90d74)
every time I try to download a file, I get an error.

**Comment by tladesignz** [comment]
Hm. With this few information, I cannot reproduce the problem.

Can you get a little more precise?
- A URL where this happens to you would be great.
- Can you describe step-by-step what you do?
- Where is this screenshot from? Can you make a bigger one with context?

The word "Plug-in" makes me a little bit wary. Did you install any Safari plug-ins?

**Comment by givememulch** [comment]
I sadly cannot send a link to the file itself, since it's between a few people and is private.

How ever, I go to an endpoint that loads a file. The endpoint is just the location for the file on the server.
But then I get this error. This screenshot is from the Onion Browser when the endpoint has loaded on my Apple Device which is on IOS 17.

**Comment by tladesignz** [comment]
Unfortunately, you didn't answer any of my questions.

If you can find a public URL, where this happens to you, I can check with my setup, and then we can see, if this a problem with your setup, or, if I can reproduce it, a problem of Onion Browser.

Please read my previous post carefully, and try to answer my questions/bullets one-by-one.
Otherwise, I will be unable to help you.

Thank you.

**Comment by tladesignz** [comment]
🤷
