### ISSUE TITLE
[Bug] Bottom toolbar disappears when more than 10 tabs are open

### ISSUE THREAD

**Issue by hellfire103** [OnionBrowser/iOS-OnionBrowser#460]
I have noticed that, if I have a lot of tabs open, the bottom bar completely disappears. Scrolling does not bring it back, and it disappears when switching tabs if I restart the app.

![IMG_6458](https://github.com/OnionBrowser/OnionBrowser/assets/67475141/9f74093e-7d3e-4f21-84eb-807656fe82c4)

**Comment by tladesignz** [comment]
Thanks for bugging me about this again! I couldn't exactly reproduce what you describe, but I found a bug which is quite the opposite: When creating a new tab, the toolbar didn't go away on scrolling. The `UIScrollViewDelegate` wasn't set in the correct order. Maybe, that's the root cause of your issue, too? I now make sure, that the delegate gets set to the scroll view.

HtH!

**Comment by hellfire103** [comment]
@tladesignz The update just came through now, and the bug seems to be fixed. Thank you!

**Comment by tladesignz** [comment]
> @tladesignz The update just came through now, and the bug seems to be fixed. Thank you!

Oh, great! Thank you very much for the feedback!
