### ISSUE TITLE
Building dependencies: libssl -> tar: Unrecognized archive format

### ISSUE THREAD

**Issue by can16358p** [OnionBrowser/iOS-OnionBrowser#64]
Hello,

I am following the procedure to build the dependencies but I'm stuck trying to build the dependencies. I've copied the latest repo and I'm executing:

canp:iOS-OnionBrowser-master Can$ bash build-libssl.sh
Downloading openssl-1.0.2a.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   316  100   316    0     0   2055      0 --:--:-- --:--:-- --:--:--  2051
Using openssl-1.0.2a.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   320  100   320    0     0   2204      0 --:--:-- --:--:-- --:--:--  2206
Using openssl-1.0.2a.tar.gz.asc

COULD NOT VERIFY PACKAGE SIGNATURE...

I then try the --noverify option but this time I get:

Using openssl-1.0.2a.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

I've tried to remove the build folder several times and try again, but I'm always getting the same result.
I'm on OS X 10.10.4.

**Comment by hanmiltonxing** [comment]
Have you solved this? I met this too. Thank you.

**Comment by can16358p** [comment]
@hanmiltonxing Nope, unfortunatelly not. It was not a mandatory project so I paused working on it. I'd be glad if someone solves it though so I can resume it.

**Comment by hanmiltonxing** [comment]
Thanks.

**Comment by mtigas** [comment]
This is normal behavior if your download failed (i.e. the download was removed). The build script will then obviously fail to unzip the file (because you downloaded an HTTP 404 and not the source tarball).

You can make the script try the download again by deleting the file from `build/src`.

You can also manually download the file from the OpenSSL site and place it in the `build/src` directory, ensuring that the filename matches the name that the script is looking for.
